PAAS-1498: Handle multiple haproxy custom rules files in jelastic pac…
Jahia/jelastic-packages pull request #108
Opened 2021-08-05 21:00 UTC by amitc-jahia

…kage

JIRA issue: https://jira.jahia.org/browse/PAAS-1498

Short description:

2021-08-06 14:06 UTC, laurentfufu requested changes

2021-08-06 14:06 UTC, laurentfufu commented on packages/jahia/rewrite-rules.yml
> +        done
I don't understand how this can works because after line 31, `rules_sets` while be something like this:
```json
{
  "rewrite-rules": "{\"file_1\": \"# this \\n# is file 1\", \"file_2\":\"# and this\\n# is file 2 and I □ unicode\"}"
}
```

so `echo $rules_sets | jq -r 'keys[]'` will output only `rewrite-rules` and we will have a a `rewrite-rules` file name with the content this content:
```
{"file_1": "# this \n# is file 1", "file_2":"# and this\n# is file 2 and I □ unicode"}
```

??

2021-08-06 14:35 UTC, laurentfufu commented on packages/jahia/rewrite-rules.yml
> +        done
forget, i'm nut, there will be no `rewrite-rules` key anymore, sorry ! :trollface:

2021-08-06 14:59 UTC, laurentfufu submitted a review, later dismissed

2021-08-06 14:59 UTC, laurentfufu commented on packages/jahia/rewrite-rules.yml
> +          echo $rules_sets | jq -r ".\"$rules_set\"" > '${globals.rules_dir}'/$rules_set.cfg
backslash escapes will stay literals here

2021-08-10 22:06 UTC, amitc-jahia commented on packages/jahia/rewrite-rules.yml
> +          echo $rules_sets | jq -r ".\"$rules_set\"" > '${globals.rules_dir}'/$rules_set.cfg
Changes have been made. Backslash escapes are being handled

Checked max line command size with config around 100k lines and it is not an issue.

2021-08-13 13:46 UTC, adoux submitted a review, later dismissed

2021-08-13 13:48 UTC, adoux commented
Approved, waiting for PAAS-1576 to be merged before merging that one

2021-08-13 14:38 UTC, kevinvandel submitted a review, later dismissed
@amitc-jahia an action is needed in the migration package to update the file structure on existing envs, otherwise when we release we would break the feature for all existing envs with a custom conf (so probably all prod envs).
Don't hesitate to reach out to Cyril if you need insight on that part.

2021-08-13 18:59 UTC, amitc-jahia commented
Migration package updated to handle custom rules for existing envs.

2021-08-13 20:03 UTC, adoux submitted a review, later dismissed

2021-08-13 20:04 UTC, adoux commented
@amitc-jahia, sorry... But conflicts :grimacing:

2021-08-13 22:24 UTC, amitc-jahia commented
Rebased

2021-08-16 09:07 UTC, kevinvandel commented
@amitc-jahia could you please squash the 2 last commits (6419c4a and 07933e9) instead of having one with ugly conflicts and another to remove them ? (you can do that with an interactive rebase or a reset HEAD).
Also it would be nice to move the `updateHAProxyRulesFile` action up in the migration package, I tried to order all actions so that we have :
1. actions that don't require anything special
2. actions that require a restart
3. restart

And I think we need to be careful about the `updateHaproxyConfig` action, which also changes the HAProxy config (and reloads it).

2021-08-16 09:07 UTC, kevinvandel requested changes
@amitc-jahia could you please squash the 2 last commits (6419c4a and 07933e9) instead of having one with ugly conflicts and another to remove them ? (you can do that with an interactive rebase or a reset HEAD).
Also it would be nice to move the `updateHAProxyRulesFile` action up in the migration package, I tried to order all actions so that we have :
1. actions that don't require anything special
2. actions that require a restart
3. restart

And I think we need to be careful about the `updateHaproxyConfig` action, which also changes the HAProxy config (and reloads it).

2021-08-16 11:05 UTC, kevinvandel commented
> And I think we need to be careful about the `updateHaproxyConfig` action, which also changes the HAProxy config (and reloads it).

@amitc-jahia I just had a closer look, and your action needs to be done before `updateHaproxyConfig`, because the filename matters to this action (so the renaming needs to be done beforehand).

2021-08-16 15:33 UTC, amitc-jahia commented
Changes made as requested regarding the commits and action in the migration package.

Also moved the action for [https://jira.jahia.org/browse/PAAS-1690](https://jira.jahia.org/browse/PAAS-1690) in the migration package before the restarts.

Each commit in the PR is a dedicated action.

2021-08-17 09:34 UTC, kevinvandel approved these changes

2021-08-17 09:34 UTC, merged