PAAS-1712: Configure Datadog APM on jahia nodes
Jahia/jelastic-packages pull request #110
Opened 2021-08-06 12:54 UTC by kevinvandel

JIRA issue: https://jira.jahia.org/browse/PAAS-1712

2021-08-06 12:55 UTC, kevinvandel commented on mixins/jahia.yml
> +    - setupDatadogAgentJahia: ${this}
FYI I chose that name to be consistent with the other actions (`setupDatadogAgentSql`, `setupDatadogAgentHaproxy`, etc.)

2021-08-09 08:45 UTC, laurentfufu requested changes

2021-08-09 08:45 UTC, laurentfufu commented on mixins/jahia.yml
> +        sed -i -E '/^JAVA_OPTS/ s/(.)$/ -Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -javaagent:/opt/tomcat/datadog/dd-java-agent.jar -Ddd.service=jah
have to escape slash chars in javaagent path or choose another delimiter

2021-08-09 09:18 UTC, laurentfufu approved these changes

2021-08-09 09:18 UTC, merged