PAAS-2996: Update SAM to 2.8.0 / 3.2.0
Jahia/jelastic-packages pull request #1111
Opened 2024-08-27 16:51 UTC by julien-gagnon

JIRA issue: https://jira.jahia.org/browse/PAAS-2996

Short description:
- Update SAM
- Decrease RenderingChain probe severity from critical to high

2024-08-28 06:31 UTC, Ronan-Gorain submitted a review, later dismissed

2024-09-03 14:48 UTC, julien-gagnon commented on packages/jahia/migrations/migrate-to-v44.yaml
> +    - if ("${globals.runningVersion}" != "${globals.requiredSamVersion}"):
Indeed, fixed :)

2024-09-11 07:20 UTC, kevinvandel requested changes

2024-09-11 07:20 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v44.yaml
> +  - updateSAM                                         # PAAS-2996
This needs to be moved to the "Actions that update modules" section. Doing this action last is the worst! (risk causing issues with the rolling restart done right after)

2024-09-11 07:23 UTC, kevinvandel approved these changes

2024-09-11 07:24 UTC, merged