PAAS-3147: lower backup impact on performances and run a GC.run befor…
Jahia/jelastic-packages pull request #1177
Opened 2024-10-22 11:15 UTC by Ronan-Gorain

…e data sync

JIRA issue: https://jira.jahia.org/browse/PAAS-3147

Short description:

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2024-10-22 12:13 UTC, julien-gagnon commented on packages/common/backup.yml
> +        if [[ "$(grep DX_VESTION /.jelenv | sed 's/.*=\(8\.1\)\..*/match/')" = "8.1" ]]; then
Typo here, should be DX_VERSION

2024-10-23 12:01 UTC, laurentfufu requested changes

2024-10-23 12:01 UTC, laurentfufu commented on packages/common/backup.yml
> +        if [[ "$(grep DX_VESTION /.jelenv | sed 's/.*=\(8\.1\)\..*/match/')" = "8.1" ]]; then
```suggestion
        if (grep -q '^DX_VERSION=8.1.' /.jelenv); then
```
looks better and I guess more functional than substite `8.1.*` to `match` and then test if if equal to `8.1` :raised_eyebrow:

2024-10-23 13:00 UTC, Ronan-Gorain commented on packages/common/backup.yml
> +        if [[ "$(grep DX_VESTION /.jelenv | sed 's/.*=\(8\.1\)\..*/match/')" = "8.1" ]]; then
indeed, don't know why first thought about the complicated way...

2024-10-24 15:08 UTC, laurentfufu approved these changes

2024-10-24 16:23 UTC, merged