PAAS-1535: fix karaf password when containing dollar sign
Jahia/jelastic-packages pull request #12
Opened 2021-04-21 21:54 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1535

Short description:
I tried to think of a simple way to do it but it was more complex than it seemed because of the `export` command in `setenv` file.
The way I choose to go with allow the user to put single/double quotes, dollar signs and other special characters in their jcustomer password.
I've tested some scenarios and it seems to work pretty well

2021-04-22 23:25 UTC, amitc-jahia reviewed
For the _reset-unomi-root-password.py_ script, I don't think we need to make any changes as it is already able to take special characters and the password doesn't get truncated. Also, in the case of password reset, the new changes would only update **UNOMI_ROOT_PASSWORD_B64** and not the **UNOMI_ROOT_PASSWORD** in the envfile.

2021-04-23 10:22 UTC, laurentfufu requested changes

2021-04-23 10:22 UTC, laurentfufu commented on assets/jcustomer/reset-unomi-root-password.py
> +        print(line)
I guess this will add ugly empty lines every time it's launched

2021-04-23 10:22 UTC, laurentfufu commented on assets/jcustomer/reset-unomi-root-password.py
> +        if "UNOMI_ROOT_PASSWORD_B64=" in line:
what about setenv without this line ?

2021-04-23 19:37 UTC, adoux commented on assets/jcustomer/reset-unomi-root-password.py
> +        print(line)
Indeed, fixed!

2021-04-23 21:10 UTC, adoux commented
> For the _reset-unomi-root-password.py_ script, I don't think we need to make any changes as it is already able to take special characters and the password doesn't get truncated. Also, in the case of password reset, the new changes would only update **UNOMI_ROOT_PASSWORD_B64** and not the **UNOMI_ROOT_PASSWORD** in the envfile.

Yeah but this is actually what we want, the `UNOMI_ROOT_PASSWORD` will be updated as it decodes UNOMI_ROOT_PASSWORD_B64 before exporting the variable.
We have to do it that way if we want to allow special characters like dollar sign, equal sign or quotes.

2021-04-23 21:11 UTC, adoux commented on assets/jcustomer/reset-unomi-root-password.py
> +        if "UNOMI_ROOT_PASSWORD_B64=" in line:
I actually forgot the migration package so you're right :man_facepalming: 
I've updated the script anyways so it will always add the two required lines at the end of the file, and I added the migration package as well

2021-04-26 08:09 UTC, laurentfufu approved these changes

2021-04-26 08:18 UTC, laurentfufu commented on assets/jcustomer/reset-unomi-root-password.py
> +export_password_line = "export UNOMI_ROOT_PASSWORD=$(echo $UNOMI_ROOT_PASSWORD_B64 | base64 -d)"
I think a newline would have been nice here

2021-04-26 14:17 UTC, adoux commented on assets/jcustomer/reset-unomi-root-password.py
> +export_password_line = "export UNOMI_ROOT_PASSWORD=$(echo $UNOMI_ROOT_PASSWORD_B64 | base64 -d)"
Done!

2021-04-26 14:48 UTC, laurentfufu approved these changes

2021-04-26 14:48 UTC, merged