PAAS-1437: Prevent MariaDB auto-restart when updating cloudlets count
Jahia/jelastic-packages pull request #13
Opened 2021-04-21 22:18 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1437

Short description:

2021-04-23 09:45 UTC, kevinvandel requested changes

2021-04-23 09:45 UTC, kevinvandel commented on mixins/mariadb.yml
> +        wget -qP /var/lib/jelastic/customizations ${baseUrl}../../assets/database/jahia_override.lib
It's forbidden to use `${baseUrl}` in a mixin (and it should be avoided in general, to prevent relative path issues).
You need to use `setGlobalRepoRootUrl` instead.

2021-04-23 15:42 UTC, amitc-jahia commented on mixins/mariadb.yml
> +        wget -qP /var/lib/jelastic/customizations ${baseUrl}../../assets/database/jahia_override.lib
Fixed

2021-04-26 06:30 UTC, kevinvandel approved these changes

2021-04-26 09:10 UTC, laurentfufu approved these changes

2021-04-26 09:22 UTC, merged