PAAS-1767: apply datadog apm settings for jahia process only when APM is
Jahia/jelastic-packages pull request #162
Opened 2021-09-30 14:11 UTC by Ronan-Gorain

enabled

JIRA issue: https://jira.jahia.org/browse/PAAS-1767

Short description:

2021-09-30 14:15 UTC, kevinvandel requested changes

2021-09-30 14:15 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v9.yaml
> +  - updateApmJavaOption                            # PAAS-1767
If only we had a specific block for all actions that require a restart... Oh wait, it's just below ! :trollface:

2021-09-30 15:07 UTC, kevinvandel submitted a review, later dismissed

2021-10-04 12:12 UTC, laurentfufu commented on mixins/jahia.yml
> +        sed -i 's/^\(JAVA_OPTS.*\)"$/\1 $APM_OPTS"/g' /opt/tomcat/conf/tomcat-env.sh
```suggestion
        echo 'APM_OPTS="-Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -javaagent:/opt/tomcat/datadog/dd-java-agent.jar -Ddd.service=jahia -Ddd.env=${env.domain}"' >> $tomcat_env
        echo '$DATADOG_APM_ENABLED && JAVA_OPTS="$JAVA_OPTS $APM_OPTS"' >> $tomcat_env
```

suggestion for readability

2021-10-04 12:12 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v9.yaml
> +        sed -i 's/^\(JAVA_OPTS.*\)"$/\1 $APM_OPTS"/g' /opt/tomcat/conf/tomcat-env.sh
```suggestion
        echo 'APM_OPTS="-Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -javaagent:/opt/tomcat/datadog/dd-java-agent.jar -Ddd.service=jahia -Ddd.env=${env.domain}"' >> $tomcat_env
        echo '$DATADOG_APM_ENABLED && JAVA_OPTS="$JAVA_OPTS $APM_OPTS"' >> $tomcat_env
```
```suggestion
        echo 'APM_OPTS="-Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -javaagent:/opt/tomcat/datadog/dd-java-agent.jar -Ddd.service=jahia -Ddd.env=${env.domain}"' >> $tomcat_env
        echo '$DATADOG_APM_ENABLED && JAVA_OPTS="$JAVA_OPTS $APM_OPTS"' >> $tomcat_env
```

2021-10-04 12:12 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v9.yaml
> +      if [ "$(grep APM_OPTS /opt/tomcat/conf/tomcat-env.sh)" == "" ];then
```suggestion
      if ! (grep -q APM_OPTS /opt/tomcat/conf/tomcat-env.sh);then
```

2021-10-04 12:16 UTC, laurentfufu commented on mixins/jahia.yml
> +        sed -i 's/^\(JAVA_OPTS.*\)"$/\1 $APM_OPTS"/g' /opt/tomcat/conf/tomcat-env.sh
`JAVA_OPTS="$JAVA_OPTS $APM_OPTS"` can also be `JAVA_OPTS+=" $APM_OPTS"`

2021-10-04 13:34 UTC, Ronan-Gorain commented on mixins/jahia.yml
> +        sed -i 's/^\(JAVA_OPTS.*\)"$/\1 $APM_OPTS"/g' /opt/tomcat/conf/tomcat-env.sh
Improvements done

2021-10-05 07:41 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v9.yaml
> +
![image](https://user-images.githubusercontent.com/48996839/135980903-0ef6dc30-313f-4d1a-af4e-66be44ee0ad7.png)

:trollface:

2021-10-05 13:44 UTC, Ronan-Gorain commented on packages/jahia/migrations/migrate-to-v9.yaml
> +
fixed

2021-10-06 09:44 UTC, laurentfufu approved these changes

2021-10-06 09:45 UTC, merged