PAAS-1739: Fix actions to use globals and add migration package to up…
Jahia/jelastic-packages pull request #212
Opened 2021-11-30 23:24 UTC by amitc-jahia

…date-events

JIRA issue: https://jira.jahia.org/browse/PAAS-1739

Short description:

2021-12-01 07:43 UTC, kevinvandel requested changes

2021-12-01 07:43 UTC, kevinvandel commented on mixins/jahia.yml
>    deleteEnvLink:
Could you please add a doc-comment specifying the parameter (`jCustomerEnv`) and the response (`${response.link_removed}`), like we do for other actions ?

2021-12-01 15:30 UTC, amitc-jahia commented on mixins/jahia.yml
>    deleteEnvLink:
Done

2021-12-01 16:02 UTC, kevinvandel approved these changes

2021-12-02 08:49 UTC, laurentfufu approved these changes

2021-12-02 08:49 UTC, merged