PAAS-1865: Add check to unmute after monitor status is OK
Jahia/jelastic-packages pull request #222
Opened 2021-12-09 21:25 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1865

Short description:

2021-12-10 08:05 UTC, kevinvandel requested changes

2021-12-10 08:05 UTC, kevinvandel commented on mixins/common.yml
> +        for (( i=1; i<=180; i++ )); do
Could you please add a comment to explain what we're doing here ? The whole action is getting quite complex, so having small comments summing up each step would we really cool :)

2021-12-10 13:31 UTC, amitc-jahia commented on mixins/common.yml
> +        for (( i=1; i<=180; i++ )); do
Done

2021-12-10 14:26 UTC, amitc-jahia commented on mixins/common.yml
> +        for (( i=1; i<=180; i++ )); do
The 180 is the number of iteration and not actually seconds. Along with the 1s sleep in the loop, the total time for the action to complete takes 5mins. If I have 300 iterations then it takes 8 mins, which is way too longer.

2021-12-10 15:02 UTC, kevinvandel commented on mixins/common.yml
> +        for (( i=1; i<=180; i++ )); do
Damn, so that means the API call takes almost 700ms ?! Sounds like a lot :grimacing: 
Anyway, thanks for the explanation. It could be worth being more accurate in the comment then, like `Once max iterations (~5mins for 180 iterations) is reached`.

2021-12-10 15:02 UTC, kevinvandel submitted a review, later dismissed

2021-12-10 15:14 UTC, amitc-jahia commented on mixins/common.yml
> +        for (( i=1; i<=180; i++ )); do
Changed

2021-12-13 11:32 UTC, adoux approved these changes

2021-12-13 12:07 UTC, merged