PAAS-1737 fix some conditionals, always set variable even if false
Jahia/jelastic-packages pull request #236
Opened 2021-12-21 16:34 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-1737

Short description:

2021-12-21 16:39 UTC, kevinvandel commented on packages/common/restore.yml
> +    # be awre that this global is a string
typo :stuck_out_tongue:

2021-12-21 16:53 UTC, laurentfufu commented on packages/common/restore.yml
> +    # be awre that this global is a string
fixed

2021-12-22 07:35 UTC, kevinvandel requested changes
I think there are other test conditions to fix:
https://github.com/Jahia/jelastic-packages/blob/b739217ee91313d70c5b89efa7ad6aec6a57b2a4/packages/common/restore.yml#L279
https://github.com/Jahia/jelastic-packages/blob/b739217ee91313d70c5b89efa7ad6aec6a57b2a4/packages/common/restore.yml#L297
https://github.com/Jahia/jelastic-packages/blob/b739217ee91313d70c5b89efa7ad6aec6a57b2a4/packages/common/restore.yml#L306

EDIT: I was wrong, in those cases the variable really contains a boolean and not a string :exploding_head:

2021-12-22 07:38 UTC, kevinvandel requested changes

2021-12-22 07:38 UTC, kevinvandel commented on packages/common/restore.yml
> +            same_jexperience_conf: false
I'm not 100% sure, but I think those 3 globals can be defined locally instead of globally (`set` instead of `setGlobals`).

2021-12-22 09:30 UTC, kevinvandel commented
>

2021-12-22 09:49 UTC, laurentfufu commented
> I think there are other test conditions to fix:
> 
> https://github.com/Jahia/jelastic-packages/blob/b739217ee91313d70c5b89efa7ad6aec6a57b2a4/packages/common/restore.yml#L279
> 
> https://github.com/Jahia/jelastic-packages/blob/b739217ee91313d70c5b89efa7ad6aec6a57b2a4/packages/common/restore.yml#L297
> 
> https://github.com/Jahia/jelastic-packages/blob/b739217ee91313d70c5b89efa7ad6aec6a57b2a4/packages/common/restore.yml#L306
> 
> EDIT: I was wrong, in those cases the variable really contains a boolean and not a string exploding_head

now using the famous `jelastic don't care about bolean or string type` form :trollface:

2021-12-22 09:50 UTC, laurentfufu commented on packages/common/restore.yml
> +            same_jexperience_conf: false
globals are required here because there are used in conditional statements later in the manifest

2021-12-22 10:11 UTC, kevinvandel submitted a review, later dismissed

2021-12-22 10:49 UTC, kevinvandel approved these changes

2021-12-22 10:49 UTC, merged