PAAS-1954: update jahia_cfg_mvnPath during onAfterRedeploy
Jahia/jelastic-packages pull request #257
Opened 2022-02-14 21:57 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1954

Short description:

2022-02-15 07:39 UTC, kevinvandel requested changes

2022-02-15 07:39 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v12.yaml
> -        service tomcat start
This will not do, because Jahia must be stopped when the lib is removed.

2022-02-15 22:16 UTC, adoux commented on packages/jahia/migrations/migrate-to-v12.yaml
> -        service tomcat start
Fixed

2022-02-16 08:19 UTC, kevinvandel approved these changes

2022-02-16 13:52 UTC, amitc-jahia approved these changes

2022-02-16 13:52 UTC, merged