PAAS-1854: handle EC deployment at jcustomer env creation
Jahia/jelastic-packages pull request #260
Opened 2022-02-16 16:54 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-1854

Short description:

2022-02-18 08:55 UTC, laurentfufu commented on mixins/elasticsearch.yml
> +        ec_deployment_id=$( echo $environment | jq -r .ec_deployment_id)
```suggestion
        ec_deployment_id=$(echo $environment | jq -r .ec_deployment_id)
```

2022-02-18 08:55 UTC, laurentfufu commented on mixins/elasticsearch.yml
> +        organization_id=$( echo $environment | jq -r .paas_organization_id)
```suggestion
        organization_id=$(echo $environment | jq -r .paas_organization_id)
```

2022-02-18 08:55 UTC, laurentfufu commented on mixins/elasticsearch.yml
> +        if [ $workflow_status != "success" ]; then
```suggestion
        if [ "$workflow_status" != "success" ]; then
```

2022-02-18 13:19 UTC, Ronan-Gorain commented on mixins/elasticsearch.yml
> +        if [ $workflow_status != "success" ]; then
Good catch. Fixed along with spaces before echo. Pushed force

2022-02-23 22:16 UTC, adoux commented on packages/jcustomer/migrations/migrate-to-v11.yaml
> +      UNOMI_ELASTICSEARCH_INDEXPREFIX: "${env.envName}"
Missing `_jc`?

2022-02-23 22:16 UTC, adoux commented on mixins/elasticsearch.yml
> +    #    workflow: terraform_apply
Forgot to uncomment?

2022-02-24 07:43 UTC, Ronan-Gorain commented on packages/jcustomer/migrations/migrate-to-v11.yaml
> +      UNOMI_ELASTICSEARCH_INDEXPREFIX: "${env.envName}"
I forgot to update this one... thanks
Fixed

2022-02-24 07:44 UTC, Ronan-Gorain commented on mixins/elasticsearch.yml
> +    #    workflow: terraform_apply
I uncommented it but forgot to push :man_facepalming:

2022-02-24 18:12 UTC, laurentfufu requested changes

2022-02-24 18:12 UTC, laurentfufu commented on mixins/elasticsearch.yml
> +        sed -i "s,curl.*9200,curl -u '${env.envName}:${globals.elasticsearch_password}' '$es_endpoint,g" /etc/systemd/system/karaf.service
I'm not sure here: it would be better here to use the `EnvironmentFile` from the `karaf.service` unit file and use these envvars in the `ExecStartPre`. Or even create an override with the right config to give us time to update this file in the `jahiastic-jcustomer` image.

2022-02-24 18:12 UTC, laurentfufu commented on packages/jcustomer/migrations/migrate-to-v11.yaml
> +      UNOMI_ELASTICSEARCH_INDEXPREFIX: "${env.envName}_jc"
not sure here: what will happen when karaf will be restarted ?

2022-02-25 10:33 UTC, Ronan-Gorain commented on mixins/elasticsearch.yml
> +    - cmd [${nodes.cp.first.id}]: |-
Fixed

2022-02-25 10:33 UTC, Ronan-Gorain commented on mixins/elasticsearch.yml
> +        sed -i "s,curl.*9200,curl -u '${env.envName}:${globals.elasticsearch_password}' '$es_endpoint,g" /etc/systemd/system/karaf.service
I used env vars instead of real values

2022-02-25 10:34 UTC, Ronan-Gorain commented on packages/jcustomer/migrations/migrate-to-v11.yaml
> +      UNOMI_ELASTICSEARCH_INDEXPREFIX: "${env.envName}_jc"
:facepalm: fixed (removed from migration package)

2022-02-25 11:23 UTC, laurentfufu requested changes

2022-02-25 11:23 UTC, laurentfufu commented on mixins/elasticsearch.yml
> +        sed -i "s,curl.*9200,curl -u \\\"\$UNOMI_ELASTICSEARCH_USERNAME:\$UNOMI_ELASTICSEARCH_PASSWORD\\\" \\\"https://\$UNOMI_ELASTICSEARCH_ADDRESSES\\\",g" /etc/systemd/system/karaf.service
variables have to be braced here :trollface:

2022-02-25 13:18 UTC, laurentfufu approved these changes

2022-02-25 13:18 UTC, merged