PAAS-1962: One-shot package to apply 8.0.3.2 patch
Jahia/jelastic-packages pull request #278
Opened 2022-03-16 09:23 UTC by kevinvandel

JIRA issue: https://jira.jahia.org/browse/PAAS-1962

2022-03-16 16:26 UTC, laurentfufu requested changes

2022-03-16 16:26 UTC, laurentfufu commented on packages/one-shot/paas-1962-apply-8032-patch.yml
> +            message: "No unomi linked"
the long sobs of the violins of autumn

2022-03-17 07:40 UTC, kevinvandel commented on packages/one-shot/paas-1962-apply-8032-patch.yml
> +            message: "No unomi linked"
fixed

2022-03-17 07:40 UTC, kevinvandel commented on packages/one-shot/paas-1962-apply-8032-patch.yml
> +        fi
fixed

2022-03-17 10:15 UTC, laurentfufu commented on packages/one-shot/paas-1962-apply-8032-patch.yml
> +            message: "Jahia version is ${globals.jahiaVersion}, not 8.0.3.0 ; aborting"
```suggestion
            message: "Jahia version is ${globals.jahiaVersion}, not 8.0.3.0 ; nothing to do"
```
for the record :trollface:

2022-03-17 10:15 UTC, laurentfufu approved these changes

2022-03-17 10:15 UTC, merged

2022-03-17 10:40 UTC, kevinvandel commented on packages/one-shot/paas-1962-apply-8032-patch.yml
> +            message: "Jahia version is ${globals.jahiaVersion}, not 8.0.3.0 ; aborting"
Number of fucks given : :zero: