PAAS-1509 Move jCustomer Jelastic packages to jelastic-packages repo
Jahia/jelastic-packages pull request #3
Opened 2021-04-07 08:20 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-1509

Short description:

2021-04-07 15:20 UTC, kevinvandel requested changes

2021-04-07 15:20 UTC, kevinvandel commented on README.md
> +This manifest is launch against a Jahia env and will link it to a jCustomer environment.
*launched
It could be nice to add a little more details to say that this installs and configures jExperience

2021-04-07 15:20 UTC, kevinvandel commented on mixins/jahia.yml
> +                jexperience_version: 1.12.3
Since those actions are very specific (and in the end we update a jCustomer env, not Jahia), I think we should keep them in the `link-to-jcustomer` package instead of putting them in the mixin

2021-04-07 15:20 UTC, kevinvandel commented on mixins/jahia.yml
> +        sed -i 's/\(\(mf\|jexperience\)\.\(unomi\|jCustomer\)Password=\)karaf/\1${globals.unomi_pwd}/' "$CONF_PATH"
`unomidns` and `unomi_pwd` could be given as arguments, instead of relying on globals

2021-04-07 15:20 UTC, kevinvandel commented on mixins/jahia.yml
> +        MODULE_URL="https://store.jahia.com/cms/mavenproxy/private-app-store/org/jahia/modules/jexperience/${globals.jexperience_version}/jexperience-${globals.jexperience_version}.jar"
`jexperience_version` could be given to the action as an argument

2021-04-07 15:20 UTC, kevinvandel commented on mixins/jahia.yml
> +        sed -i 's/\(\(mf\|jexperience\)\.\(unomi\|jCustomer\)Password=\)karaf/\1${globals.unomi_pwd}/' "$CONF_PATH"
A little off-topic (we can create a dedicated ticket for that), but we can drop the "mf" and "unomi" stuff now, we missed that when we cleaned the code after dropping marketing-factory.

2021-04-07 16:27 UTC, laurentfufu commented on README.md
> +It's a merge of what where in previous _paas_*_ and _cloudr-scripts_ repos.
done

2021-04-07 16:27 UTC, laurentfufu commented on README.md
> +#### JCustomer
done

2021-04-07 16:27 UTC, laurentfufu commented on README.md
> +This manifest is launch against a Jahia env and will link it to a jCustomer environment.
done

2021-04-07 17:12 UTC, laurentfufu commented on mixins/jahia.yml
> +                jexperience_version: 1.12.3
done
also remove the `installJexperience` in order to use the more generic `upgradeJahiaModule` from mixins/jahia.yml instead.

2021-04-07 17:57 UTC, laurentfufu commented on mixins/jahia.yml
> +        sed -i 's/\(\(mf\|jexperience\)\.\(unomi\|jCustomer\)Password=\)karaf/\1${globals.unomi_pwd}/' "$CONF_PATH"
as the actions move from mixins to manifest, i should be ok to keep globals
(well isn't the same action because module install is handle by a generic action, but a dedicated action for jexperience configuration)

2021-04-07 20:09 UTC, adoux approved these changes

2021-04-08 06:57 UTC, kevinvandel commented on README.md
> +#### JCustomer
not really, since you kept the capital `J` on jCustomer, but I'll pass

2021-04-08 06:57 UTC, kevinvandel approved these changes

2021-04-08 06:57 UTC, merged

2021-04-08 07:49 UTC, laurentfufu commented on README.md
> +#### JCustomer
oups :disappointed: