PAAS-2070 Use CRLF for haproxy's httpchk headers
Jahia/jelastic-packages pull request #358
Opened 2022-05-25 11:59 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-2070

Short description:

2022-05-25 12:13 UTC, kevinvandel requested changes

2022-05-25 12:13 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v15.yaml
> +  - haproxyCheckConformRFC                                # COPS-571
Wrong ticket ID :stuck_out_tongue:

2022-05-25 12:15 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v15.yaml
> +  - haproxyCheckConformRFC                                # COPS-571
fixed :trollface:

2022-05-25 14:27 UTC, Ronan-Gorain submitted a review, later dismissed

2022-05-25 14:27 UTC, Ronan-Gorain commented on packages/jahia/migrations/migrate-to-v15.yaml
> +          sed -i "s/admin-stat-password/$stats_pwd/g" /etc/haproxy/haproxy.cfg.jahia/jahia-cloud.cfg
I might be wrong, but it looks like the case where the auth basic is enabled is not handled (including  user env-admin password  )

2022-05-25 15:39 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v15.yaml
> +          sed -i "s/admin-stat-password/$stats_pwd/g" /etc/haproxy/haproxy.cfg.jahia/jahia-cloud.cfg
should be better now :trollface:

2022-05-30 09:18 UTC, kevinvandel approved these changes

2022-05-30 11:31 UTC, kevinvandel approved these changes

2022-05-30 11:31 UTC, merged