PAAS-1916: Use Jahia API to handle actions on modules
Jahia/jelastic-packages pull request #362
Opened 2022-06-01 22:25 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1916

Short description:
* Tried to make actions as generic as possible so they can be reused for other needs
* Made sure the `install-module.yml` wasn't used anywhere and renamed/updated it to be used to uninstall jExperience on linked Jahia envs when deleting a jCustomer env

2022-06-02 08:14 UTC, kevinvandel requested changes

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +          STARTED)
I'm 99% sure we'll have issues with this. For instance I know that in some cases the module status is "INSTALLED", while it's actually started... I'll try to reproduce this.

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +            echo "401 unauthorized"
generic message, you know the drill

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +  uninstallModuleCompletely:
Why not just `uninstallModule` ?

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +            echo "401 unauthorized"
you know what

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +        module_version: ${this.module_version}
That may but out-of-scope, but I'm wondering if we shouldn't also make sure that the module isn't installed in a version above the one we are about to install, to avoid downgrading it if that's the case.

2022-06-02 08:14 UTC, kevinvandel commented on packages/common/restore.yml
> +            module: jexperience
Parameters name seem wrong (should be `module_name` and `module_version` from what I see)

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +    #   - module_name: the module to upgrade
From what I understand, the `module_name` must be what seems to be called the "symbolic name", so maybe rename it to `module_symname` to make things clear? Or at least updated the comment.

2022-06-02 08:14 UTC, kevinvandel commented on packages/one-shot/ccm-103-update-to-tomcat-9-0-54.yaml
> +        - upgradeModule:
Parameters name must be updated too.

2022-06-02 08:14 UTC, kevinvandel commented on packages/jahia/link-to-jcustomer.yml
> +  - upgradeModule:
Parameters name must be updated too.

2022-06-02 08:14 UTC, kevinvandel commented on packages/jahia/manage-module.yml
> +        version: ${settings.moduleVersion}
Wrong parameters name.

2022-06-02 08:14 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v11.yaml
> +            - upgradeModule:
Parameters name must be updated too.

2022-06-02 08:14 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v9.yaml
> +    - upgradeModule:
Parameters name must be updated too.

2022-06-02 08:14 UTC, kevinvandel commented on mixins/jahia.yml
> +    #   - module_name: the module to upgrade
Note that this comment applies to other actions too, but I'm too lazy to copy my comment everywhere :p

2022-06-02 08:22 UTC, kevinvandel commented on mixins/jahia.yml
> +          STARTED)
OK so I only reproduce this behaviour with the `cluster:bundle-list` command, so I guess we'll be good.
```
$ curl -s -H "authorization: APIToken $token" http://localhost:8080/modules/api/bundles/org.jahia.modules/distributed-sessions/*/_info | jq
{
  "browsing.45955": {
    "org.jahia.modules/distributed-sessions/3.2.1": {
      "type": "MODULE",
      "osgiState": "ACTIVE",
      "moduleState": "STARTED"
    }
  },
  "processing.45954": {
    "org.jahia.modules/distributed-sessions/3.2.1": {
      "type": "MODULE",
      "osgiState": "ACTIVE",
      "moduleState": "STARTED"
    }
  }
}
```
```
fraise@dx()> bundle:list -s | grep dist
118 │ Active   │  90 │ 3.2.1           │ distributed-sessions
fraise@dx()> cluster:bundle-list -s default | grep dist
118 │ Installed │     │ cluster/local │         │ 3.2.1                 │ distributed-sessions
```

2022-06-02 15:59 UTC, adoux commented on mixins/jahia.yml
> +  checkIfModuleIsInstalled:
Nope, it's gonna be used in PAAS-2061

2022-06-02 16:00 UTC, adoux commented on mixins/jahia.yml
> +            echo "401 unauthorized"
Fixed

2022-06-02 16:00 UTC, adoux commented on mixins/jahia.yml
> +    - log: Module ${this.module_name} v${this.module_version} has been installed on ${this.target}
Oops, oversight

2022-06-02 16:00 UTC, adoux commented on packages/one-shot/ccm-103-update-to-tomcat-9-0-54.yaml
> +        - upgradeModule:
Oversight because old package but it's better to update it indeed. Fixed

2022-06-02 16:01 UTC, adoux commented on packages/jahia/manage-module.yml
> +        version: ${settings.moduleVersion}
Oversight, fixed

2022-06-02 16:01 UTC, adoux commented on packages/jahia/migrations/migrate-to-v11.yaml
> +            - upgradeModule:
Oversight because old package but it's better to update it indeed. Fixed

2022-06-02 16:01 UTC, adoux commented on packages/jahia/migrations/migrate-to-v9.yaml
> +    - upgradeModule:
Oversight because old package but it's better to update it indeed. Fixed

2022-06-07 11:18 UTC, kevinvandel commented on mixins/jahia.yml
> +        module_symname: ${this.module_name}
You forgot to rename to module_symname here and below

2022-06-07 11:18 UTC, kevinvandel commented on mixins/jahia.yml
> +  uninstallModuleCompletely:
I'm still waiting for an answer :stuck_out_tongue:

2022-06-07 11:18 UTC, kevinvandel commented on mixins/jahia.yml
> +        module_version: ${this.module_version}
@adoux didn't you tell me you would do it ?

2022-06-07 16:37 UTC, adoux commented on mixins/jahia.yml
> +  uninstallModuleCompletely:
True, makes more sense. Fixed!

2022-06-07 16:38 UTC, adoux commented on mixins/jahia.yml
> +        module_version: ${this.module_version}
I did, but forgot :man_shrugging: 
Did it in the `checkIfModuleIsInstalled` action, which makes more sense to me

2022-06-08 07:40 UTC, kevinvandel commented on mixins/jahia.yml
> +        module_version: ${this.module_version}
There are two issues:
- in the case we don't install the target module version because a more recent version is installed, `upgradeModule` will fail at `checkIfModuleVersionIsInstalled` and `checkIfModuleVersionIsStarted` steps (if I'm not mistaken)
- you check the "most recent installed version", but we would also need to check it is running ; in the end what we need is the "latest _running_ version"

2022-06-08 08:44 UTC, laurentfufu requested changes
looks nice but I don't understand the point of modifying the v9 and v11 migration manifests :grey_question:

2022-06-08 08:44 UTC, laurentfufu commented on mixins/jahia.yml
> +          echo "download failed"
if _download failed_ the action will stop here (with success) because the case isn't handle with an `if ("${response.out}" == "download failed")` like _error_ output is.

2022-06-09 08:09 UTC, kevinvandel requested changes

2022-06-09 08:09 UTC, kevinvandel commented on mixins/jahia.yml
> +    # Installs the specified version of a module and deletes all the previous versions if installed.
"deletes all the previous versions if installed" isn't really true (in some cases we may uninstall more recent versions)
Also I think that adding some detail about the various cases (module is already installed but not running, or running in a newer version than the target one) wouldn't hurt

2022-06-09 13:33 UTC, adoux commented on mixins/jahia.yml
> +        module_version: ${this.module_version}
Indeed, it's been improved now

2022-06-09 13:34 UTC, adoux commented on mixins/jahia.yml
> +    # Installs the specified version of a module and deletes all the previous versions if installed.
I updated comments, added new ones, and improved the upgradeModule action so we make sure we are running the right version before uninstalling the other ones

2022-06-09 15:20 UTC, kevinvandel submitted a review, later dismissed

2022-06-10 07:42 UTC, Ronan-Gorain commented
I have one concern about the checkModule action. I think it's not possible to know is a specific version is installed or not. So if I want to install a specific version of the module but there is already another version installed and running, I have no way to know if the version I want to install is already installed if it's not running.

2022-06-10 13:37 UTC, adoux commented
> I have one concern about the checkModule action. I think it's not possible to know is a specific version is installed or not. So if I want to install a specific version of the module but there is already another version installed and running, I have no way to know if the version I want to install is already installed if it's not running.

I added a `checkVersionOfModule` action and improved the `installModule` action to not reinstall the module if the version is already installed/running

2022-06-10 14:04 UTC, Ronan-Gorain approved these changes

2022-06-10 14:04 UTC, merged