PAAS-1855 Create Augmented Search install package
Jahia/jelastic-packages pull request #386
Opened 2022-06-23 07:39 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-1855

Short description:

2022-06-23 07:43 UTC, kevinvandel submitted a review, later dismissed

2022-07-07 08:50 UTC, kevinvandel requested changes

2022-07-07 08:50 UTC, kevinvandel commented on packages/jahia/augmented-search-install.yml
> +            - setGlobals:  # if jahia < 8.1.2 jContent have to be upgraded
*has :grin:

2022-07-07 08:50 UTC, kevinvandel commented on packages/jahia/augmented-search-install.yml
> +            moduleVersion: ${globals.jcontent_ver}
Is it really useful to define a `jcontent_ver` global ? Couldn't we just put 2.7.0 here ?

2022-07-07 08:50 UTC, kevinvandel commented on packages/jahia/augmented-search-install.yml
> +        echo $JEL_ENV_ROLE
Isn't it already done in a previous PR by Axel ?

2022-07-07 09:08 UTC, kevinvandel approved these changes

2022-07-07 09:09 UTC, merged

2022-07-07 09:10 UTC, laurentfufu commented on packages/jahia/augmented-search-install.yml
> +            moduleVersion: ${globals.jcontent_ver}
all module versions are defined in `determineModulesVersions`, I think it's better that way even if indeed here, the global `jcontent_ver` is only set up and used once