PAAS-2057: Enable Datadog APM by default
Jahia/jelastic-packages pull request #391
Opened 2022-06-27 14:43 UTC by kevinvandel

JIRA issue: https://jira.jahia.org/browse/PAAS-2057

2022-06-27 15:04 UTC, Ronan-Gorain requested changes

2022-06-27 15:04 UTC, Ronan-Gorain commented on packages/jahia/migrations/migrate-to-v16.yaml
> -  # Restart action:
If you remove this, jahia, I fear 7 environments won't be restarted because the removeModulesFolderAndRestartAllJahia action only take care of jahia 8 environments

2022-06-28 06:43 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v16.yaml
> -  # Restart action:
Indeed, I didn't see the condition on Jahia 8. I'll rework that.

2022-06-28 11:42 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v16.yaml
> -  # Restart action:
Fixed !

2022-06-28 15:45 UTC, adoux approved these changes

2022-06-28 15:45 UTC, merged