PAAS-1960: Handle Augmented search module at backup restore
Jahia/jelastic-packages pull request #395
Opened 2022-06-29 15:02 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-1960

Short description:

2022-06-30 08:29 UTC, laurentfufu commented on packages/common/restore.yml
> +              moduleSymname: augmented-search
if AS on the target env was initially present but not started, maybe we can avoid to trigger a full reindex just before stop the module ?

2022-06-30 08:29 UTC, laurentfufu commented on packages/common/restore.yml
> +            moduleSymname: augmented-search
`installOrUpgradeModule` already use this action

2022-06-30 08:29 UTC, laurentfufu commented on mixins/jahia.yml
> +          fi
`getAugSearchConnectionName` can already do that (and not used anywhere in this PR)

2022-06-30 12:36 UTC, Ronan-Gorain commented on packages/common/restore.yml
> +            moduleSymname: augmented-search
removed

2022-06-30 12:37 UTC, Ronan-Gorain commented on packages/common/restore.yml
> +              moduleSymname: augmented-search
You are right, I add a step to remove all indices before either trigger a reindexation or stopping the module.

2022-06-30 15:29 UTC, laurentfufu requested changes

2022-06-30 15:29 UTC, laurentfufu commented on mixins/jahia.yml
> +        done
```suggestion
        curl -u "$es_login:$es_password" -XDELETE "$es_endpoint/${jahia_cfg_elasticsearch_prefix}_*"
```
Should do the trick (perhaps check that `jahia_cfg_elasticsearch_prefix` has the expected value as long as you do the delete with the elastic account).

At worst leave it like that but still fix the `jq --arg pattern "$jahia_cfg_elasticsearch_prefix_."` otherwise it will delete indices not related :trollface:

2022-07-01 09:03 UTC, Ronan-Gorain commented on mixins/jahia.yml
> +        done
I added a check and fixed the jq pattern arg

2022-07-01 09:03 UTC, Ronan-Gorain commented on mixins/jahia.yml
> +        done
I did not use ${jahia_cfg_elasticsearch_prefix} because it's interpreted by jelastic

2022-07-01 15:08 UTC, laurentfufu commented on mixins/jahia.yml
> +    # Set the jahia-cloud_augmented-search connexion from elasticsearch-connector module
Unrelated comment :trollface: 

Furthermore, this action could be agnostic and delete the env's indices whether they are for AS or jCustomer ?

2022-07-04 09:51 UTC, Ronan-Gorain commented on mixins/jahia.yml
> +    # Set the jahia-cloud_augmented-search connexion from elasticsearch-connector module
Renamed in purgeEnvIndicesInES and moved to mixins/elasticsearch.yml
Updated patter from /${jahia_cfg_elasticsearch_prefix}__as_*  to /${jahia_cfg_elasticsearch_prefix}__*

2022-07-04 11:51 UTC, laurentfufu approved these changes

2022-07-04 11:51 UTC, merged