Paas 2022 dd apm j customer
Jahia/jelastic-packages pull request #396
Opened 2022-06-29 15:32 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2022

Short description:

2022-06-29 15:36 UTC, kevinvandel requested changes

2022-06-29 15:36 UTC, kevinvandel commented on mixins/jcustomer.yml
> +        ${DATADOG_APM_ENABLED:-true} && echo 'JAVA_OPTS+=" $APM_OPTS"' >> $setenv
```suggestion
        echo '${DATADOG_APM_ENABLED:-true} && JAVA_OPTS+=" $APM_OPTS"' >> $setenv
```

2022-06-29 15:36 UTC, kevinvandel commented on packages/jcustomer/migrations/migrate-to-v14.yaml
> +          ${DATADOG_APM_ENABLED:-true} && echo 'JAVA_OPTS+=" $APM_OPTS' >> $setenv
```suggestion
          echo '${DATADOG_APM_ENABLED:-true} && JAVA_OPTS+=" $APM_OPTS' >> $setenv
```

2022-06-29 19:43 UTC, adoux commented on mixins/jcustomer.yml
> +        ${DATADOG_APM_ENABLED:-true} && echo 'JAVA_OPTS+=" $APM_OPTS"' >> $setenv
stupid me :man_facepalming: 
Fixed

2022-06-29 19:43 UTC, adoux commented on packages/jcustomer/migrations/migrate-to-v14.yaml
> +          ${DATADOG_APM_ENABLED:-true} && echo 'JAVA_OPTS+=" $APM_OPTS' >> $setenv
Fixed

2022-06-30 06:25 UTC, kevinvandel approved these changes

2022-06-30 06:25 UTC, merged