PAAS-2106: Update EC score/topology before restore if needed
Jahia/jelastic-packages pull request #425
Opened 2022-07-14 12:29 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-2106

Short description:

2022-07-15 13:56 UTC, Ronan-Gorain requested changes

2022-07-15 13:56 UTC, Ronan-Gorain commented on packages/common/restore.yml
> +          timeout=600 # 10 minutes
It takes more than 10 min for an ES cluster to resize. I suggest to set the same value as the one in runESCircleCIPipeline in mixin/elasticsearch.yaml (20 minutes)

2022-07-15 22:59 UTC, amitc-jahia commented on packages/common/restore.yml
> +          timeout=600 # 10 minutes
Yes it does take longer than 10 minutes. Discussed with @laurentfufu that 20 minutes wait would be long for the restore process and decided to have a wait of 5-10 minutes and then restore the backup anyways.

@laurentfufu - should we have it as 20 instead of 10?

2022-07-18 07:44 UTC, laurentfufu commented on packages/common/restore.yml
> +          timeout=600 # 10 minutes
Yes, the maximum 10 minutes wait allows us to have the assurance of having at least 1 node corresponding to the new topology and the work of copying the shards (in the case of a shared network) already well advanced. The idea here is not to waste too much time when restoring a snapshot.

2022-07-18 08:03 UTC, Ronan-Gorain approved these changes

2022-07-18 08:03 UTC, merged

2022-07-18 08:35 UTC, laurentfufu requested changes

2022-07-18 08:35 UTC, laurentfufu commented on packages/common/restore.yml
> +        current_score=$(( (current_total_shards/ratio) + ((current_total_shards%ratio) > 0 )))
Is this really working ?

you should better use bash _indirect reference_ here:
```suggestion
        if $ec_deployment_mutualized; then
          ratio=${JEL_ENV_ROLE}_mutualized
        else
          ratio=$${JEL_ENV_ROLE}_dedicated
        fi

        # Get the total shards and score before the restore
        current_total_shards=$(curl -sS -u $ec_admin_credentials https://$UNOMI_ELASTICSEARCH_ADDRESSES/_cluster/stats | jq -r '.indices.shards.total')
        current_score=$(( (current_total_shards/${!ratio}) + ((current_total_shards%${!ratio}) > 0 )))
```

2022-07-18 14:52 UTC, amitc-jahia commented on packages/common/restore.yml
> +        current_score=$(( (current_total_shards/ratio) + ((current_total_shards%ratio) > 0 )))
This actually works as confirmed.