PAAS-2030: Hide secrets in packages and mixins from jelastic console …
Jahia/jelastic-packages pull request #446
Opened 2022-07-29 23:18 UTC by amitc-jahia

…logs in datadog

JIRA issue: https://jira.jahia.org/browse/PAAS-2030

Short description:

2022-08-02 09:13 UTC, Ronan-Gorain requested changes
Other comments : 
mixins/common.yml    
 - Vault token is not hidden line 401                         
 - globals.vaultSecretData is not renamed line 925 and 941     
mixins/jahia.yml    
 - this.__secret__pat_token is directly used line 1339    
    
In onBeforeInstall section of install packages, variables __secret__* should be defined for sensitive informations like datadogapikey, db password and all other kind of sensitive info.
    
From what I remember, there is no need to rename packages paramters. Did you find out it was necessary ? Or was the ticket not clear about it ? If not necessary, I suggest to rollback because this will require to update everything on front side.

2022-08-02 21:51 UTC, amitc-jahia commented on mixins/common.yml
> -        vaultSecretData: ${response.out}
Fixed

2022-08-02 21:51 UTC, amitc-jahia commented on mixins/jcustomer.yml
> +            __secret__newPasswordB64 = "${this.new_password_b64}";
Fixed

2022-08-02 21:51 UTC, amitc-jahia commented on mixins/mariadb.yml
> +        __secret__password="${this.__secret__password}"
Fixed

2022-08-02 21:51 UTC, amitc-jahia commented on packages/jahia/install.yml
> -  db_pass: ${fn.password(20)}
Fixed

2022-08-02 21:56 UTC, amitc-jahia commented
Other comments :
    mixins/common.yml
    Vault token is not hidden line 401
    ------> Fixed
    globals.vaultSecretData is not renamed line 925 and 941
    ------> Fixed
    mixins/jahia.yml
    this.__secret__pat_token is directly used line 1339
    ------> Fixed

In onBeforeInstall section of install packages, variables secret* should be defined for sensitive informations like datadogapikey, db password and all other kind of sensitive info.
------> Updated other variables in the install package with sensitive data

From what I remember, there is no need to rename packages paramters. Did you find out it was necessary ? Or was the ticket not clear about it ? If not necessary, I suggest to rollback because this will require to update everything on front side.
------> My bad. Reverted the packages parameters.

2022-08-04 07:23 UTC, Ronan-Gorain requested changes
Everything is ok, except the vaultAppRoleLogin action description that was not updated and still says that the action return a global named vaultToken instead of __secret__vaultToken .
sorry, I forgot to mention it in my previous review.

2022-08-04 12:29 UTC, amitc-jahia commented
> Everything is ok, except the vaultAppRoleLogin action description that was not updated and still says that the action return a global named vaultToken instead of __secret__vaultToken . sorry, I forgot to mention it in my previous review.

Fixed

2022-08-04 12:54 UTC, Ronan-Gorain approved these changes

2022-08-04 12:54 UTC, merged