PAAS-1590: Check if righsubnets don't overlap with env subnet in IPse…
Jahia/jelastic-packages pull request #45
Opened 2021-06-02 12:20 UTC by amitc-jahia

…c package

JIRA issue: https://jira.jahia.org/browse/PAAS-1590

Short description:

2021-06-03 08:39 UTC, laurentfufu requested changes

2021-06-03 08:39 UTC, laurentfufu commented on packages/jahia/ipsec.yml
> +        cat $conf_tmpfile | grep rightsubnet | cut -d'=' -f2 | tr -d ' ' | uniq >> $subnets_file
2 things bother me here:
* possible commented `rightsubnet` line will be taken into account
* `rightsubnet` can be in the form `<ip subnet>[[<proto/port>]][,...]` so this will work only with one entry (ip or subnet notation)

2021-06-04 21:08 UTC, amitc-jahia commented on packages/jahia/ipsec.yml
> +        cat $conf_tmpfile | grep rightsubnet | cut -d'=' -f2 | tr -d ' ' | uniq >> $subnets_file
Fixed

2021-06-07 09:00 UTC, laurentfufu requested changes

2021-06-07 09:00 UTC, laurentfufu commented on packages/jahia/ipsec.yml
> +        grep 'rightsubnet' $conf_tmpfile | grep -v '#' | grep -o "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,\}" | uniq >> $subnets_file
```suggestion
        grep 'rightsubnet' $conf_tmpfile | grep -v '#' | grep -Eo "([0-9]{1,3}\.){3}[0-9]{1,3}(\/[0-9]{1,})?" | uniq >> $subnets_file
```
imo, grouping the first 3 bytes and using grep's switch `-E` in order to not have to backslash brackets will help readability for this regex. As the network mask bits is optional (strongswan will assume it's `/32` then), I also update this part of the regex.

2021-06-07 09:00 UTC, laurentfufu commented on packages/jahia/ipsec.yml
> +        ipconflict -qf $subnets_file $env_ip
Not sure about testing all `rightsubnet` in one time because each entry will be tested against each other and not only against the jelastic/env's subnets. Customer may be wrong itself add why not having something like `10.100.0.0/16,10.100.2.0/24` and this will trigger an error telling that this "overlaps with Env subnet".

2021-06-07 22:52 UTC, amitc-jahia commented on packages/jahia/ipsec.yml
> +        ipconflict -qf $subnets_file $env_ip
Fixed

2021-06-07 22:52 UTC, amitc-jahia commented on packages/jahia/ipsec.yml
> +        grep 'rightsubnet' $conf_tmpfile | grep -v '#' | grep -o "[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\/[0-9]\{1,\}" | uniq >> $subnets_file
Fixed

2021-06-08 07:44 UTC, laurentfufu approved these changes

2021-06-08 07:45 UTC, merged