PAAS-2131 bump to SAM 2.2.0 for jahia 8.1.2+
Jahia/jelastic-packages pull request #465
Opened 2022-08-09 16:19 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-2131

Short description:

2022-08-09 21:08 UTC, amitc-jahia requested changes

2022-08-09 21:08 UTC, amitc-jahia commented on packages/jahia/consistency-check.yml
> +                            expectedVersion: 2.2.0
Please update the action description to reflect correct SAM version as per Jahia version

2022-08-09 21:08 UTC, amitc-jahia commented on packages/jahia/migrations/migrate-to-v17.yaml
> +            - enableHaproxyHealthcheck
New migration package (v18) is needed for this as the release is already prepared.

2022-08-10 08:31 UTC, laurentfufu commented on packages/jahia/consistency-check.yml
> +                            expectedVersion: 2.2.0
done !

2022-08-10 08:31 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v17.yaml
> +            - enableHaproxyHealthcheck
indeed, I fall into the trap every time :upside_down_face:

2022-08-10 08:35 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v17.yaml
> +            - enableHaproxyHealthcheck
Fool me once, shame on you ; fool me twice, shame on me :trollface:

2022-08-10 12:52 UTC, kevinvandel submitted a review, later dismissed

2022-08-11 09:35 UTC, kevinvandel requested changes

2022-08-11 09:35 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v18.yaml
> +          jps: "${globals.repoRootUrl}/packages/jahia/jahia-rolling-restart.yml"
This can be removed

2022-08-11 09:35 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v18.yaml
> +  jahiaRollingRestartNeeded: "false"
This can be removed

2022-08-11 09:46 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v18.yaml
> +  jahiaRollingRestartNeeded: "false"
done

2022-08-11 09:46 UTC, kevinvandel approved these changes

2022-08-11 09:47 UTC, merged