PAAS-2145 fix redeploy/upgrade breaking APM, set apm in setenv before restart karaf on install
Jahia/jelastic-packages pull request #467
Opened 2022-08-10 15:05 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-2145

Short description:

2022-08-10 15:19 UTC, kevinvandel requested changes
We need to add an action to the migration package to reinstall the APM when it's missing

2022-08-10 16:56 UTC, laurentfufu commented
a fixAPM action have been added to migration v15 manifest

2022-08-11 06:27 UTC, Ronan-Gorain commented on packages/jcustomer/migrations/migrate-to-v15.yaml
> +        apm_loaded: ${response.apm_loaded}
This variables seems to be unused

2022-08-11 07:47 UTC, laurentfufu commented on packages/jcustomer/migrations/migrate-to-v15.yaml
> +        apm_loaded: ${response.apm_loaded}
it is now 6 feet under

2022-08-11 07:51 UTC, Ronan-Gorain approved these changes

2022-08-11 08:02 UTC, merged