Paas 2144 pat120
Jahia/jelastic-packages pull request #468
Opened 2022-08-11 12:33 UTC by kevinvandel

JIRA issue: https://jira.jahia.org/browse/PAAS-2144

2022-08-12 09:09 UTC, Ronan-Gorain requested changes

2022-08-12 09:09 UTC, Ronan-Gorain commented on packages/jahia/consistency-check.yml
>          - if( ${globals.isLowerThan8100} ):
This variable is not declared yet in this action, and is defined line 116
I feel like there is a confusion with variables, the  previous line should not be updated but the b variable 2 lines before should.

2022-08-16 07:52 UTC, kevinvandel commented on packages/jahia/consistency-check.yml
>          - if( ${globals.isLowerThan8100} ):
Fixed

2022-08-16 09:37 UTC, Ronan-Gorain approved these changes

2022-08-16 09:37 UTC, merged