Paas 2028 upgrade python
Jahia/jelastic-packages pull request #470
Opened 2022-08-16 01:59 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2028

Short description:

2022-08-16 22:31 UTC, amitc-jahia requested changes

2022-08-16 22:31 UTC, amitc-jahia commented on mixins/common.yml
> +    - setGlobalRepoRootUrl
"setGlobalRepoRootUrl" action is not needed here

2022-08-16 22:31 UTC, amitc-jahia commented on mixins/common.yml
> +        rpm -ivh /root/python-${PYTHON_MAJOR_VERSION}.${PYTHON_MINOR_VERSION}.rpm || exit 1
After installation, the rpm file should be removed from the node

2022-08-16 22:31 UTC, amitc-jahia commented on mixins/common.yml
> +        pip install --upgrade pip || exit 1
After upgrading python and pip, already installed modules are not retained

2022-08-16 22:31 UTC, amitc-jahia commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Target here should be only "bl" nodeGroup

2022-08-16 22:31 UTC, amitc-jahia commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Target here should be the nodeId

2022-08-16 22:31 UTC, amitc-jahia commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Target here should be only "bl" nodeGroup

2022-08-16 22:31 UTC, amitc-jahia commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Target here should be only "sqldb" nodeGroup

2022-08-16 22:31 UTC, amitc-jahia commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Target here should be the nodeId

2022-08-16 22:31 UTC, amitc-jahia commented on packages/jahia/update-events.yml
> +        target: "bl, sqldb"
Target here should be only "sqldb" nodeGroup

2022-08-17 05:16 UTC, adoux commented on mixins/common.yml
> +    - setGlobalRepoRootUrl
Good catch, fixed!

2022-08-17 05:16 UTC, adoux commented on mixins/common.yml
> +        rpm -ivh /root/python-${PYTHON_MAJOR_VERSION}.${PYTHON_MINOR_VERSION}.rpm || exit 1
Good catch, thought I did it, fixed!

2022-08-17 05:27 UTC, adoux commented on mixins/common.yml
> +        pip install --upgrade pip || exit 1
I don't think it's an issue actually.
I compared the list of modules in one of my environments running with Python 3.6 and there is 109 modules, coming from these commands:
```
python3 -m pip install requests boto3 "azure==4.0.0" adal
```
which is run by the backup/restore package so it will be installed anyway when required, and:
```
python3 -m pip install requests
```
which is run by the `installPapiScript` action that is called in `onAfterRedeployContainer` event, which means it'll be run for any container being redeployed (and I added it to the `onAfterServiceScaleOut`).

So I don't think it's an issue for redeploy/upgrades, but it was definitely missing from the migration package so I fixed it

2022-08-17 05:30 UTC, adoux commented
> The "installPapiScript" action imports the "requests" module which will not be taken into account in the new way of installing python. Retaining the already installed modules must also be addressed in cases of redeploy and upgrade(only Jahia and jCustomer nodes) too. Maybe in the "onBeforeRedeployContainer" event an action can be added to retain this information and use it in the "onAfterRedeployContainer" event.

As said in my response to one of your comment, I don't think it's an issue since the installed modules are only the ones that are installed by the backup/restore package and by the `installPapiScript` action, that are both already run during redeploy or backup/restore.
Do you agree or have I misunderstood something?

2022-08-17 05:30 UTC, adoux commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Stupid copy/paste, good call! Fixed

2022-08-17 05:30 UTC, adoux commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Stupid copy/paste, good call! Fixed

2022-08-17 05:30 UTC, adoux commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Stupid copy/paste, good call! Fixed

2022-08-17 05:30 UTC, adoux commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Stupid copy/paste, good call! Fixed

2022-08-17 05:30 UTC, adoux commented on packages/jahia/update-events.yml
> +          target: "bl, sqldb"
Stupid copy/paste, good call! Fixed

2022-08-17 05:30 UTC, adoux commented on packages/jahia/update-events.yml
> +        target: "bl, sqldb"
Stupid copy/paste, good call! Fixed

2022-08-24 20:23 UTC, amitc-jahia commented on mixins/common.yml
> +        pip install --upgrade pip || exit 1
Yes indeed, my bad i missed the generic onAfterRedeployContainer event.

2022-08-24 20:24 UTC, amitc-jahia commented
> > The "installPapiScript" action imports the "requests" module which will not be taken into account in the new way of installing python. Retaining the already installed modules must also be addressed in cases of redeploy and upgrade(only Jahia and jCustomer nodes) too. Maybe in the "onBeforeRedeployContainer" event an action can be added to retain this information and use it in the "onAfterRedeployContainer" event.
> 
> As said in my response to one of your comment, I don't think it's an issue since the installed modules are only the ones that are installed by the backup/restore package and by the `installPapiScript` action, that are both already run during redeploy or backup/restore. Do you agree or have I misunderstood something?



Yes indeed, my bad i missed the generic onAfterRedeployContainer event.

2022-08-24 20:24 UTC, amitc-jahia approved these changes

2022-08-24 20:24 UTC, merged