Paas 2084
Jahia/jelastic-packages pull request #475
Opened 2022-08-19 16:46 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-2084

Short description:

2022-08-22 08:28 UTC, kevinvandel requested changes

2022-08-22 08:28 UTC, kevinvandel commented on mixins/jahia.yml
> +              organization=$(echo "${user.email}" | cut -d'@' -f1)
Can't we use the `ORGANIZATION_NAME` node group data instead?

2022-08-22 08:28 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v18.yaml
> +              organization=$(echo "${user.email}" | cut -d'@' -f1)
Same thing, I think we should use `ORGANIZATION_NAME` node group data instead.

2022-08-22 08:28 UTC, kevinvandel commented on packages/common/restore.yml
> +  saveScreebConfig:
This was the job of https://jira.jahia.org/browse/PAAS-2105 :stuck_out_tongue:

2022-08-22 13:24 UTC, amitc-jahia commented on mixins/jahia.yml
> +              organization=$(echo "${user.email}" | cut -d'@' -f1)
Yes indeed fetching it from node group data is much better. Fixed

2022-08-22 13:24 UTC, amitc-jahia commented on packages/jahia/migrations/migrate-to-v18.yaml
> +              organization=$(echo "${user.email}" | cut -d'@' -f1)
Fixed

2022-08-22 13:25 UTC, amitc-jahia commented on packages/common/restore.yml
> +  saveScreebConfig:
As discussed, the backup-restore part for Screeb will be handled in this ticket.

2022-08-22 14:10 UTC, Ronan-Gorain commented on packages/jahia/migrations/migrate-to-v18.yaml
> +        - script: |-
It could be better to reuse setJahiaUserFeedbacksConfig
Doesn't matter if the version check is done twice, code is not duplicated

2022-08-22 14:22 UTC, amitc-jahia commented on mixins/jahia.yml
> +            config_file="/data/digital-factory-data/karaf/etc/org.jahia.services.env.cfg"
Indeed, better to have a check before adding the config lines.

2022-08-22 23:01 UTC, amitc-jahia commented on mixins/jahia.yml
> +            config_file="/data/digital-factory-data/karaf/etc/org.jahia.services.env.cfg"
Fixed

2022-08-22 23:01 UTC, amitc-jahia commented on packages/jahia/migrations/migrate-to-v18.yaml
> +        - script: |-
Fixed

2022-08-23 06:56 UTC, Ronan-Gorain approved these changes

2022-08-23 06:57 UTC, Ronan-Gorain approved these changes

2022-08-23 06:58 UTC, merged