PAAS-2064: remove kibana-dashboards-provider and jexperience-dashboard when unlinking or deleting jCustomer
Jahia/jelastic-packages pull request #476
Opened 2022-08-23 12:18 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2064

Short description:

2022-09-02 12:29 UTC, laurentfufu commented on mixins/jahia.yml
> +      sed -i "s,.*\(kibana_dashboards_provider.\)\(kibanaURL\|kibanaUser\|kibanaPassword\|kibanaSpace\).*,\1\2=,g" $cfg_file
```suggestion
      sed -E 's:(^\s*kibana_dashboards_provider\.)(kibana(URL|User|Password|Space)).*:\1\2=:' -i $cfg_file
```

2022-09-02 12:29 UTC, laurentfufu commented on packages/jahia/unlink-jahia-jcustomer.yml
> +    - name: isUnomiEnvDeletiion
`Deletiion` ?

2022-09-02 12:29 UTC, laurentfufu commented on mixins/jcustomer.yml
> +                    'isUnomiEnvDeletiion': true,
`Deletiion` ?

2022-09-02 14:54 UTC, adoux commented on mixins/jahia.yml
> +      sed -i "s,.*\(kibana_dashboards_provider.\)\(kibanaURL\|kibanaUser\|kibanaPassword\|kibanaSpace\).*,\1\2=,g" $cfg_file
Good call, change made!

2022-09-02 14:54 UTC, adoux commented on packages/jahia/unlink-jahia-jcustomer.yml
> +    - name: isUnomiEnvDeletiion
Ooooops, fixed!

2022-09-02 14:54 UTC, adoux commented on mixins/jcustomer.yml
> +                    'isUnomiEnvDeletiion': true,
Ooooops, fixed!

2022-09-05 12:08 UTC, laurentfufu requested changes

2022-09-05 12:08 UTC, laurentfufu commented on packages/jahia/unlink-jahia-jcustomer.yml
> +      type: radiolist
A `radiolist` with only one item is a little weird.
Maybe you should use type `toggle` instead and change the `if` condition (line 32) to use boolean.

2022-09-07 08:53 UTC, laurentfufu requested changes

2022-09-07 19:03 UTC, adoux commented on packages/jahia/unlink-jahia-jcustomer.yml
> +  - if (${settings.isUnomiEnvDeletion} != true):
Fixed

2022-09-08 09:53 UTC, laurentfufu approved these changes

2022-09-08 09:55 UTC, merged