PAAS-2147: install and configure kibana-dashboard-provider if upgrading from Jahia 7 to Jahia 8
Jahia/jelastic-packages pull request #487
Opened 2022-08-30 22:49 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2147

Short description:

2022-09-05 11:58 UTC, kevinvandel requested changes

2022-09-05 11:58 UTC, kevinvandel commented on mixins/jahia.yml
> +        return {"result": 0, "out": jCustomerLinked};
Why not use `getEnvLinkedJcustomer` action ?

2022-09-05 11:58 UTC, kevinvandel commented on mixins/jahia.yml
> +  setupKibanaDashboard:
I'm not sure about this mixin, because:
1. it is used only once
2. the name is very confusing with `configureKibanaDashboard`

In the end I think it's better to do things directly in the upgrade package.

2022-09-05 11:58 UTC, kevinvandel commented on mixins/jahia.yml
> +          jcustomer_env: ${this.jCustomerLinked}
Ugh, I didn't see that one before, but the case of `jcustomer_env` sucks :grimacing: (should be `jCustomerEnv`)

2022-09-05 13:12 UTC, kevinvandel commented on mixins/jahia.yml
> +          jcustomer_env: ${this.jCustomerLinked}
Renaming done in this PR: https://github.com/Jahia/jelastic-packages/pull/493
You'll have to rebase and take that into account.

2022-09-06 14:33 UTC, adoux commented on mixins/jahia.yml
> +        return {"result": 0, "out": jCustomerLinked};
Good call, fixed

2022-09-06 14:34 UTC, adoux commented on mixins/jahia.yml
> +  setupKibanaDashboard:
I renamed both actions so it's not confusing anymore, but I keep the action in a mixin since it's used in the upgrade package and the migrate-to-18 one

2022-09-06 14:34 UTC, adoux commented on mixins/jahia.yml
> +          jcustomer_env: ${this.jCustomerLinked}
Done

2022-09-06 15:01 UTC, kevinvandel requested changes

2022-09-06 15:01 UTC, kevinvandel commented on packages/jahia/upgrade.yml
> +      a: ${nodes.proc.first.customitem.nodeVersion}
It's very dangerous to rely on the placeholder `nodeVersion` here, we should do it differently (currently it contains the value we expect, but this is an accident and Jelastic is supposed to fix it).

2022-09-06 15:07 UTC, adoux commented on packages/jahia/upgrade.yml
> +      a: ${nodes.proc.first.customitem.nodeVersion}
Good catch, fixed

2022-09-06 15:09 UTC, kevinvandel approved these changes

2022-09-06 15:09 UTC, merged