PAAS-2151: check if module started after installation, refactor checkModule action
Jahia/jelastic-packages pull request #496
Opened 2022-09-07 02:53 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2151

Short description:

2022-09-07 09:20 UTC, kevinvandel requested changes

2022-09-07 09:20 UTC, kevinvandel commented on mixins/jahia.yml
> +            message: "An error occurred during module startup."
This needs to be done only when `startModule` is true.
Maybe we can factorize the code by doing the check at the end of the action, outside the "if" condition.

2022-09-07 09:20 UTC, kevinvandel commented on mixins/jahia.yml
> +              running_version_key_value="'runningVersion': '$running_version',"
I don't get the point of this `running_version_key_value` variable :thinking:

2022-09-07 14:54 UTC, adoux commented on mixins/jahia.yml
> +            message: "An error occurred during module startup."
Good catch, done!

2022-09-07 15:03 UTC, kevinvandel commented on mixins/jahia.yml
> +              running_version_key_value="'runningVersion': '$running_version',"
That was not really my point. What I don't get is why you put the whole JSON string, instead of just storing the version, and then use it in the "echo", like it was before actually.

2022-09-07 18:20 UTC, adoux commented on mixins/jahia.yml
> +              running_version_key_value="'runningVersion': '$running_version',"
I changed the way we were doing and force the declaration of all 4 globals, with empty string if needed

2022-09-08 07:04 UTC, kevinvandel approved these changes

2022-09-08 07:04 UTC, merged