PAAS-1512 Move cloud-scripts Jelastic packages to jelastic-packages repo
Jahia/jelastic-packages pull request #5
Opened 2021-04-09 10:04 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-1512

Short description:

2021-04-09 13:45 UTC, kevinvandel requested changes

2021-04-09 13:45 UTC, kevinvandel commented on packages/augsearch/augsearch-redeploy-es-nodes.yml
> +  - redeployEsNodes
This will not work, because those 2 actions needs to be performed on the AS env, but here they'll be run on the Jahia env.
That's why in the original package I did it like that:
```
  - install:
      jps: "${baseUrl}/../es-nodes/redeploy-es-nodes.yml"
      envName: ${settings.augSearchEnvName}
```

2021-04-09 13:45 UTC, kevinvandel commented on README.md
> +#### augsearch/augsearch-redeploy-es-nodes.yml
If we really wanted to comply with the rules, we should put this package inside the "jahia" folder, since it needs to be applied to the Jahia env (and not the AS one, which is given in a separate custom argument).
But since this one is really particular, maybe we can leave it here for now (we'll have to redo all this when integrating AS for real anyway).

2021-04-09 14:13 UTC, laurentfufu commented on packages/augsearch/augsearch-redeploy-es-nodes.yml
> +  - redeployEsNodes
as requested, the manifest is now deleted

2021-04-09 14:14 UTC, laurentfufu commented on README.md
> +#### augsearch/augsearch-redeploy-es-nodes.yml
as requested, the manifest is now deleted

2021-04-09 14:19 UTC, kevinvandel approved these changes

2021-04-12 11:43 UTC, Ronan-Gorain approved these changes

2021-04-12 11:43 UTC, merged