PAAS-2158: update thread-dump.sh script in migration package
Jahia/jelastic-packages pull request #508
Opened 2022-09-14 16:02 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2158

Short description:

2022-09-16 14:55 UTC, laurentfufu requested changes

2022-09-16 14:55 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v19.yaml
> +      script_md5=004842341907ba770d42fc4c7a19efd9
I guess this will have to be updated (cf https://github.com/Jahia/jahiastic-jahia/pull/215)

2022-09-19 14:33 UTC, adoux commented on packages/jahia/migrations/migrate-to-v19.yaml
> +      script_md5=004842341907ba770d42fc4c7a19efd9
Done

2022-09-21 14:17 UTC, laurentfufu approved these changes

2022-09-21 14:17 UTC, merged