PAAS-1609: Rework all version comparisons to use 'compareVersions' ac…
Jahia/jelastic-packages pull request #52
Opened 2021-06-15 14:41 UTC by amitc-jahia

…tion

JIRA issue: https://jira.jahia.org/browse/PAAS-1609

Short description:

2021-06-16 07:55 UTC, laurentfufu commented on packages/common/restore.yml
> +            sed -i "s|^cluster.node.serverId.*|cluster.node.serverId = $short_name|" $STACK_PATH/conf/digital-factory-config/jahia/jahia.node.properties
shouldn't this be done whatever the version of jahia ?

2021-06-16 07:55 UTC, laurentfufu commented on packages/jahia/perf-test-step1.yml
> +  - if( ${globals.isVersionHigherThan8000} || ${globals.isVersionEqualTo8000}):
maybe we can do something like that here (or create `isVersionHigherOrEqual` and `isVersionLowerOrEqual`, sure they will be useful)

```suggestion
  - Compare:
      a: ${globals.jahiaVersion}
      b: 8.0.0.0
      res: isVersionHigherOrEqual8000

  - if(globals.isVersionHigherOrEqual8000 >= 0):
```

2021-06-16 08:18 UTC, kevinvandel requested changes

2021-06-16 08:18 UTC, kevinvandel commented on packages/common/restore.yml
> +            sed -i "s|^cluster.node.serverId.*|cluster.node.serverId = $short_name|" $STACK_PATH/conf/digital-factory-config/jahia/jahia.node.properties
Yes indeed, we should completely remove this condition since we don't have any version older than 7.3
It seems we forgot to delete it before.

2021-06-16 08:18 UTC, kevinvandel commented on packages/jahia/perf-test-step1.yml
> +  - if( ${globals.isVersionHigherThan8000} || ${globals.isVersionEqualTo8000}):
Personally I think that creating `isVersionHigherOrEqual` and `isVersionLowerOrEqual` (and also renaming the others 2 methods into `isVersionStrictlyHigher` and `isVersionStriclyLower`) would help make things easier to understand ; btw that's what we did on the frontend side. When I started my review I had to check the action definition to see if the condition was strict or not...

An alternative in your case @amitc-jahia would have been to check this instead:
```
  - isVersionLower:
      a: ${globals.jahiaVersion}
      b: 8.0.0.0
      res: isVersionLowerThan8000
  - if( ! ${globals.isVersionLowerThan8000} ):
```
But this isn't the easiest to understand, having multiple actions with explicit names is the way to go IMHO.

2021-06-16 15:20 UTC, amitc-jahia commented on packages/common/restore.yml
> +            sed -i "s|^cluster.node.serverId.*|cluster.node.serverId = $short_name|" $STACK_PATH/conf/digital-factory-config/jahia/jahia.node.properties
Fixed

2021-06-16 15:21 UTC, amitc-jahia commented on packages/jahia/perf-test-step1.yml
> +  - if( ${globals.isVersionHigherThan8000} || ${globals.isVersionEqualTo8000}):
Fixed

2021-06-16 15:38 UTC, kevinvandel requested changes

2021-06-16 15:38 UTC, kevinvandel commented on mixins/common.yml
> +    - if (${globals.isVersionLowerOrEqualComparison} == -1 || ${globals.isVersionLowerOrEqualComparison} == 0):
```suggestion
    - if (${globals.isVersionLowerOrEqualComparison} <= 0):
```

2021-06-16 15:38 UTC, kevinvandel commented on mixins/common.yml
> +    - if (${globals.isVersionLowerOrEqualComparison} == 1 || ${globals.isVersionLowerOrEqualComparison} == 0):
```suggestion
    - if (${globals.isVersionLowerOrEqualComparison} >= 0):
```

2021-06-16 16:00 UTC, amitc-jahia commented on mixins/common.yml
> +    - if (${globals.isVersionLowerOrEqualComparison} == -1 || ${globals.isVersionLowerOrEqualComparison} == 0):
FIxed

2021-06-16 16:00 UTC, amitc-jahia commented on mixins/common.yml
> +    - if (${globals.isVersionLowerOrEqualComparison} == 1 || ${globals.isVersionLowerOrEqualComparison} == 0):
FIxed

2021-06-17 06:57 UTC, kevinvandel approved these changes

2021-06-17 06:57 UTC, merged