PAAS-2138: improve checkDatadogAgentCheck by checking monitors status
Jahia/jelastic-packages pull request #520
Opened 2022-09-26 12:40 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-2138

Short description:

2022-09-26 15:30 UTC, laurentfufu requested changes

2022-09-26 15:30 UTC, laurentfufu commented on mixins/common.yml
> +        monitors_in_error=$(echo $monitors_in_error | jq '.[0].aggregator.service_checks[] | select (.status != 0) | .check')
```suggestion
        monitors_in_error=$(echo $check_response | jq '.[0].aggregator.service_checks[] | select (.status != 0) | .check')
```

2022-09-27 07:21 UTC, Ronan-Gorain commented on mixins/common.yml
> +        monitors_in_error=$(echo $monitors_in_error | jq '.[0].aggregator.service_checks[] | select (.status != 0) | .check')
Good catch :pray: 
FIx with push-force

2022-09-28 07:42 UTC, laurentfufu approved these changes

2022-09-28 07:42 UTC, merged