Paas 1681
Jahia/jelastic-packages pull request #547
Opened 2022-10-28 14:08 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-1681

Short description:

2022-11-04 10:48 UTC, laurentfufu requested changes
Shouldn't `applicationcontext-purge-jobs.xml` be enabled on processing during an install?

I'm also thinking about backup and restore:
* If the file is present (and normally activated because it is saved on the processing) in the backup, it should be deactivated on the browsings
* If the file is not present because of a "old" backup, we can probably forgot about browsing nodes, but it should be downloaded and activated on the processing

2022-11-08 16:22 UTC, adoux commented
> Shouldn't `applicationcontext-purge-jobs.xml` be enabled on processing during an install?
> 
> I'm also thinking about backup and restore:
> 
> * If the file is present (and normally activated because it is saved on the processing) in the backup, it should be deactivated on the browsings
> * If the file is not present because of a "old" backup, we can probably forgot about browsing nodes, but it should be downloaded and activated on the processing

Changes made

2022-11-09 09:11 UTC, laurentfufu requested changes

2022-11-09 09:11 UTC, laurentfufu commented on packages/common/restore.yml
> +          curl -fSsLo ${file}-disabled $url || exit 1
i'm not sure it will be useful to download the file on browsing

2022-11-09 09:11 UTC, laurentfufu commented on packages/common/restore.yml
> +          url=${globals.repoRootUrl}/packages/jahia/migrations/v20_assets/applicationcontext-purge-jobs.xml-disabled
I guess the file should be promoted to a real asset and should be available in `${globals.repoRootUrl}/assets/jahia`

2022-11-09 13:40 UTC, adoux commented on packages/common/restore.yml
> +          curl -fSsLo ${file}-disabled $url || exit 1
I removed this

2022-11-09 13:40 UTC, adoux commented on packages/common/restore.yml
> +          url=${globals.repoRootUrl}/packages/jahia/migrations/v20_assets/applicationcontext-purge-jobs.xml-disabled
Good call, done

2022-11-09 14:41 UTC, laurentfufu approved these changes

2022-11-09 14:41 UTC, merged