PAAS-1643: Package to fix 'context-patch' index configuration
Jahia/jelastic-packages pull request #57
Opened 2021-06-17 18:23 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1643

Short description:

2021-06-17 21:43 UTC, adoux requested changes

2021-06-17 21:43 UTC, adoux commented on packages/one-shot/fix-context-patch-index-configuraton.yml
> +      curl -s $UNOMI_ELASTICSEARCH_ADDRESSES/_cat/indices | awk '{print $3}' | grep 'dx_*'
You can use filters directly in the request, like `es:9200/_cat/indices?h=index`, that way you don't need to `awk`

(Same thing for the next curls)

2021-06-17 21:43 UTC, adoux commented on packages/one-shot/fix-context-patch-index-configuraton.yml
> +      curl -s -XDELETE $UNOMI_ELASTICSEARCH_ADDRESSES/context-patch
I think we should make sure that the previous command is OK before deleting the index, just in case.

Overall I think you can add something like `| exit 1` after curl POST/PUT commands since they all depend on the previous ones

2021-06-18 15:10 UTC, amitc-jahia commented on packages/one-shot/fix-context-patch-index-configuraton.yml
> +      curl -s $UNOMI_ELASTICSEARCH_ADDRESSES/_cat/indices | awk '{print $3}' | grep 'dx_*'
Done

2021-06-18 15:10 UTC, amitc-jahia commented on packages/one-shot/fix-context-patch-index-configuraton.yml
> +      curl -s -XDELETE $UNOMI_ELASTICSEARCH_ADDRESSES/context-patch
Changes made

2021-06-18 18:57 UTC, adoux approved these changes

2021-06-18 18:57 UTC, merged