PAAS-1885: add jahia option to prevent APM to block tomcat stop and i…
Jahia/jelastic-packages pull request #594
Opened 2022-12-21 08:54 UTC by Ronan-Gorain

…ncrease SHUTDOWN_WAIT value

JIRA issue: https://jira.jahia.org/browse/PAAS-1885

Short description:

2022-12-21 13:20 UTC, kevinvandel requested changes

2022-12-21 13:20 UTC, kevinvandel commented on mixins/jahia.yml
> +        grep -q '^APM_OPTS=*' ${tomcat_env} || echo 'APM_OPTS="-Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -javaagent:/opt/tomcat/datadog/dd-java-age
Isn't there a typo ?
I guess it should be `-Ddd.resolver.use.loadclass=false` instead of `-Ddd..loadclass=false`

2022-12-21 13:23 UTC, Ronan-Gorain commented on mixins/jahia.yml
> +        grep -q '^APM_OPTS=*' ${tomcat_env} || echo 'APM_OPTS="-Ddd.profiling.enabled=true -XX:FlightRecorderOptions=stackdepth=256 -Ddd.logs.injection=true -javaagent:/opt/tomcat/datadog/dd-java-age
Good catch...

Fixed and pushed force

2022-12-21 13:57 UTC, kevinvandel approved these changes

2022-12-22 15:11 UTC, laurentfufu approved these changes

2022-12-22 15:11 UTC, merged