PAAS-2243: Fix issues with dnsmasq when an IPSec connection has a sla…
Jahia/jelastic-packages pull request #603
Opened 2022-12-23 13:22 UTC by amitc-jahia

…sh in the name

JIRA issue: https://jira.jahia.org/browse/PAAS-2243

Short description:

2022-12-23 14:09 UTC, laurentfufu requested changes
we should also do something to set up the missing dnsmasq conf file otherwise the problem will only be solved the next time ipsec reconnects

2022-12-23 14:09 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v21.yaml
> +        curl -fLSso $target ${baseUrl}/v7_assets/ipsec_updown.sh || exit 1
```suggestion
        curl -fLSso $target ${baseUrl}/v21_assets/ipsec_updown.sh || exit 1
```

2022-12-23 17:45 UTC, amitc-jahia commented on packages/jahia/migrations/migrate-to-v21.yaml
> +        curl -fLSso $target ${baseUrl}/v7_assets/ipsec_updown.sh || exit 1
Fixed. As discussed, without restarting strongswan service, steps added in the migration package to create the missing dnsmasq conf file in existing envs and reload the dnsmasq service.

2022-12-27 08:39 UTC, kevinvandel approved these changes

2022-12-27 08:39 UTC, merged