PAAS-2193: Handle s3 buckets to store logs
Jahia/jelastic-packages pull request #610
Opened 2023-01-19 09:21 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-2193

Short description:

2023-01-23 09:44 UTC, laurentfufu requested changes

2023-01-23 09:44 UTC, laurentfufu commented on assets/common/rclone-logs.sh
> +nodeId=$(hostname | sed 's/^[[:alpha:]]\+\([[:digit:]]\+\).*/\1/' | tr [A-Z] [a-z])
why convert uppercase to lowercase (from an hostname) to get the node ID ?

Also I gess something like this will be more readable
```suggestion
nodeId=$(hostname | sed -r 's/^node([0-9]+)-.*$/\1/'
```

2023-01-23 09:44 UTC, laurentfufu commented on mixins/common.yml
> +        return {"result": 0};
So the credentials will be visible in `/jahia/administration/systemInfos` ? This didn't looks a good idea to me.

I would prefer them to be hardcoded in the rclone configuration file owned by the root user.

2023-01-24 12:12 UTC, Ronan-Gorain commented on assets/common/rclone-logs.sh
> +nodeId=$(hostname | sed 's/^[[:alpha:]]\+\([[:digit:]]\+\).*/\1/' | tr [A-Z] [a-z])
Fixed

2023-01-24 12:13 UTC, Ronan-Gorain commented on mixins/common.yml
> +        return {"result": 0};
Creds are now hardcoded in rclone config.
Only the bucket name remain as env var as it can't be set in rclone config

2023-01-24 14:03 UTC, laurentfufu approved these changes

2023-01-24 14:07 UTC, merged