PAAS-2265: increase proxySQL max_connections to 100 to match jdbc limit
Jahia/jelastic-packages pull request #615
Opened 2023-01-23 14:26 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-2265

Short description:

2023-01-23 16:04 UTC, laurentfufu requested changes

2023-01-23 16:04 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v22.yaml
> +        sed -i 's/max_connections =.*/max_connections = 100/g' /etc/proxysql.cnf
This file is taked into account only if proxysql is started with proxysql database yet.
Also this sed will be dangerous (if the previous situation become true) because it will also increase max_connections for the datadog user.
And `g` flag is not needed :trollface:

2023-01-23 16:20 UTC, Ronan-Gorain commented on packages/jahia/migrations/migrate-to-v22.yaml
> +        sed -i 's/max_connections =.*/max_connections = 100/g' /etc/proxysql.cnf
The datadog user setting is not catched by the regex as there are multiple spaces before the "="

2023-01-23 16:24 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v22.yaml
> +        sed -i 's/max_connections =.*/max_connections = 100/g' /etc/proxysql.cnf
even worst for easily understand what this sed is exactly doing (from my point of view :trollface: )

about the first comment, i wanted to say "This file is taked into account only if proxysql is started **without** proxysql database yet."

2023-01-24 10:14 UTC, laurentfufu approved these changes

2023-01-24 10:15 UTC, merged