PAAS-2230: Add new package to update the geoname index for a jCustome…
Jahia/jelastic-packages pull request #641
Opened 2023-02-15 01:54 UTC by amitc-jahia

…r environment

JIRA issue: https://jira.jahia.org/browse/PAAS-2230

Short description:

2023-02-15 11:08 UTC, Ronan-Gorain approved these changes

2023-02-15 11:08 UTC, Ronan-Gorain commented on packages/jcustomer/geoname-index-and-aliases-update.yml
> +            index_aliases=$(curl -fLSsu "$login:$password" "$es_endpoint/$index/_alias" | jq -r .[].aliases | jq keys[])
I just think it may be nice to add a logging of existing aliases. This way, if the package fails when recreating aliases, it will allow us to retrieve existing ones and recreate them more easily. What do you think ?

2023-02-15 11:08 UTC, Ronan-Gorain requested changes
I approved instead of requesting changes... sorry :/

2023-02-15 21:24 UTC, amitc-jahia commented on packages/jcustomer/geoname-index-and-aliases-update.yml
> +  - ForEach(nodes.cp):
Fixed

2023-02-15 21:25 UTC, amitc-jahia commented on packages/jcustomer/geoname-index-and-aliases-update.yml
> +            index_aliases=$(curl -fLSsu "$login:$password" "$es_endpoint/$index/_alias" | jq -r .[].aliases | jq keys[])
Changed. Logging alias name when removing the aliases.

2023-02-16 03:02 UTC, adoux approved these changes

2023-02-16 03:03 UTC, merged