PAAS-2309: Update HAProxy config to not index technical domains
Jahia/jelastic-packages pull request #654
Opened 2023-03-16 02:40 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-2309

Short description:

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2023-03-16 12:52 UTC, laurentfufu requested changes

2023-03-16 12:52 UTC, laurentfufu commented on assets/haproxy/robots_noindex.http
In fact in the ticket PAAS-2309 example I use the `.http` extension but that's something I should have removed. Indeed, the `.http` extension implies that the file also contains the HTTP code and the response headers which is not the case here.

2023-03-16 12:52 UTC, laurentfufu commented on packages/jahia/migrations/migrate-to-v23.yaml
> +        if ( ! grep -q "$HAPROXY_DIR/robots_noindex.http" $HAPROXY_JAHIA_CONF ); then
cf my comment about the file name

2023-03-16 17:15 UTC, amitc-jahia commented on assets/haproxy/robots_noindex.http
> +# ¯_(ツ)_/¯
Fixed

2023-03-16 17:15 UTC, amitc-jahia commented on assets/haproxy/haproxy-jahia-cloud.cfg
> +    http-request return status 200 content-type "text/plain" file "/etc/haproxy/robots_noindex.http" hdr "cache-control" "no-cache" if is_robots_txt  is_host_technical_domain !is_x-forwarded-host_set
Fixed

2023-03-17 10:19 UTC, laurentfufu requested changes

2023-03-17 10:19 UTC, laurentfufu commented on assets/haproxy/robots_noindex.txt
> +# ¯_(ツ)_/¯
```suggestion
# ¯\_(ツ)_/¯
```
or
```suggestion
```
&nbsp;  
`¯\_(ツ)_/¯`

2023-03-17 12:43 UTC, amitc-jahia commented on assets/haproxy/robots_noindex.txt
> +# ¯_(ツ)_/¯
Fixed

2023-03-17 13:02 UTC, laurentfufu submitted a review, later dismissed

2023-03-17 13:12 UTC, laurentfufu approved these changes

2023-03-17 13:12 UTC, merged