PAAS-1605: Replace 'mode' parameter with nodes counts and sizes
Jahia/jelastic-packages pull request #66
Opened 2021-06-22 11:53 UTC by kevinvandel

JIRA issue: https://jira.jahia.org/browse/PAAS-1605

2021-06-22 13:11 UTC, jahia-carp commented on README.md
> +| processingNodeSize | Size of Jahia processing node (`small`, `medium` or `large`)                             |
missing haproxyNodeCount / sqldbNodeCount and sqldbNodeSize parameters

2021-06-22 13:42 UTC, kevinvandel commented on README.md
> +| processingNodeSize | Size of Jahia processing node (`small`, `medium` or `large`)                             |
fixed

2021-06-22 14:09 UTC, jahia-carp approved these changes

2021-06-23 09:59 UTC, laurentfufu approved these changes

2021-06-23 10:42 UTC, laurentfufu requested changes
XMX expressed like `[0-9].[0-9]G` will not work and tomcat will fail :(

2021-06-23 11:03 UTC, kevinvandel commented
@laurentfufu XMX values fixed

2021-06-23 11:42 UTC, laurentfufu approved these changes

2021-06-24 09:29 UTC, merged