Paas 2330: remove sudo permissions
Jahia/jelastic-packages pull request #670
Opened 2023-04-05 05:20 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-2330

2023-04-06 12:25 UTC, laurentfufu commented on mixins/jahia.yml
> +              sudo -u tomcat touch $config_file
I'm just taking this example but this is present in several places in the PR: wouldn't it be better to add the `user: tomcat` parameter to the `cmd` block?

2023-04-06 12:25 UTC, laurentfufu commented on mixins/common.yml
>    installBackupTools:
it's not a criticism and  it's open to discussion: backups and restores will now be run by the `root` user instead of the `tomcat` user or `mysql` user?

2023-04-06 15:57 UTC, adoux commented on mixins/common.yml
> +    - cmd [${this}]: sed -i 's;^jelastic:.*;jelastic:x:0:0::/root:/bin/bash;' /etc/passwd
Stupid oversight after I updated updated the action, fixed

2023-04-06 16:02 UTC, adoux commented on mixins/jahia.yml
> +              sudo -u tomcat touch $config_file
You're right it's definitely better to keep using the application user directly, I changed this everywhere

2023-04-06 16:07 UTC, adoux commented on mixins/common.yml
>    installBackupTools:
Yes it will.
I don't think it would be an issue but maybe I forgot about something?

If we want to keep using the application users to backup/restore (which I don't mind if there is a valid reason) then I will have to change the `jelastic_backup` folder (now located in `/root` with this PR) to something like `/var/jelastic_backup` and chown the folder to the user with uid 700 (haproxy, mysql, tomcat... Which also means changing the uid/gid of `karaf` user for jcustomer nodes). Or I could just `chmod 755` but not ideal.

Anyway, if you think it is better to not use root then I will make the appropriate changes

2023-04-07 07:58 UTC, laurentfufu commented on mixins/common.yml
>    installBackupTools:
it's ok for me, I was mainly asking if it was intentional or not :stuck_out_tongue:

2023-04-07 08:41 UTC, laurentfufu requested changes

2023-04-07 08:41 UTC, laurentfufu commented on mixins/jahia.yml
> +          sudo service tomcat start
Isn't the user `tomcat` supposed to have no more `sudo` rights?

Either this kind of action should be performed in `root` or the `tomcat`/`mysql` users should still be given the strict rights they need (as managing their own services).

2023-04-07 08:41 UTC, laurentfufu commented on packages/common/backup.yml
> +      user: mysql
is this one done with the `mysql` on purpose ?

2023-04-07 10:07 UTC, laurentfufu requested changes

2023-04-10 19:14 UTC, adoux commented on packages/common/backup.yml
> +      user: mysql
The command was run with `sudo -u mysql`.
I tried to run it as root on one of my envs and I got:
```
root@node51763-adoux1-adoux ~ $ ionice -n 5 mariabackup --backup --target-dir=/tmp/test --compress --compress-threads=2 --user mysql
[00] 2023-04-10 19:12:57 Connecting to MySQL server host: localhost, user: mysql, password: not set, port: not set, socket: not set
[00] 2023-04-10 19:12:57 Failed to connect to MySQL server: Access denied for user 'mysql'@'localhost'.
```

I know this is something we could fix but I don't see the point since we were already using `mysql` to run mariabackup

2023-04-10 19:15 UTC, adoux commented on packages/common/restore.yml
>          chown tomcat: digital-factory-data.tar.gz digital-factory-config.tar.gz jahia-env-vars.gz
Nope it isn't good catch, fixed!

2023-04-10 19:17 UTC, adoux commented on packages/common/restore.yml
>          rm digital-factory-data.tar.gz
Done

2023-04-10 19:18 UTC, adoux commented on packages/common/restore.yml
> +        chown tomcat: /data
forgot the `-R` parameter

2023-04-10 19:23 UTC, adoux commented on packages/common/restore.yml
> +      user: tomcat
That's what I did before you told me that it would be better to run the cmd block as `tomcat` as opposed to use `sudo -u tomcat` :-)
But I agree so it's fixed now

2023-04-10 19:24 UTC, adoux commented on packages/common/restore.yml
>          chown tomcat:tomcat -R /opt/tomcat/conf
that `chown` was useless indeed, fixed

2023-04-10 19:25 UTC, adoux commented on packages/common/restore.yml
>          chown haproxy: haproxy.tar.gz
Nope, good catch again

2023-04-10 19:25 UTC, adoux commented on packages/common/restore.yml
> +        chown -R haproxy: /etc/haproxy
Indeed, useless `chown`, fixed

2023-04-10 19:29 UTC, adoux commented on packages/common/backup.yml
> +      user: mysql
But if you think we should then I can fix this

2023-04-11 08:37 UTC, laurentfufu commented on mixins/jahia.yml
> +          sudo service tomcat start
sure, but I'm afraid that the `TOMCAT_SERVICE` command group that we're interested in in this example is not set up anywhere in the PR, unless it's set up automatically by jelastic (it would seem dangerous for jelastic to decide for us the system rights of the application user, but why not) ?

2023-04-11 08:40 UTC, laurentfufu commented on packages/common/backup.yml
> +      user: mysql
it's ok for me, I just wanted to know if it was done on purpose

2023-04-11 08:43 UTC, laurentfufu commented on packages/common/restore.yml
> +      user: tomcat
still have to be sure that, with this PR, the `tomcat` user will be able to `sudo touch` :trollface:

2023-04-11 09:01 UTC, laurentfufu submitted a review, later dismissed

2023-04-11 14:55 UTC, adoux commented on mixins/jahia.yml
> +          sudo service tomcat start
Very good catch, fixed!

2023-04-11 15:38 UTC, laurentfufu reviewed
now just need a more global `set<blabla>SudoPermissions` action :)

2023-04-11 15:38 UTC, laurentfufu commented on mixins/haproxy.yml
> +        if ! grep -qE "^haproxy "; then
missing the file to grep

2023-04-11 16:47 UTC, adoux commented
> now just need a more global `set<blabla>SudoPermissions` action :)

Done!

2023-04-11 17:52 UTC, julien-gagnon approved these changes

2023-04-11 17:53 UTC, merged