PAAS-2321: disable operations on cloud managed modules
Jahia/jelastic-packages pull request #697
Opened 2023-04-25 18:51 UTC by julien-gagnon

JIRA issue: https://jira.jahia.org/browse/PAAS-2321

Short description: disable operations on cloud managed modules

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2023-04-26 07:39 UTC, kevinvandel requested changes

2023-04-26 07:39 UTC, kevinvandel commented on packages/jahia/consistency-check.yml
> -    - checkSAM
We need to keep the complete checks for PAT and SAM. Actually, they are the most important ones.

2023-04-26 07:39 UTC, kevinvandel commented on packages/jahia/consistency-check.yml
>              moduleSymname: jexperience
Could you please add checks about `jexperience-dashboards` and `kibana-dashboards-provider`? (they should be running)

2023-04-26 07:39 UTC, kevinvandel commented on packages/jahia/consistency-check.yml
> -                message: "Running augmented-search version is ${globals.runningVersion} instead of ${this.expectedASVersion}"
We need to keep checking that `elasticsearch-connector` and `augmented-search` are running. Not only `database-connector`.

2023-04-26 19:02 UTC, julien-gagnon commented on packages/jahia/consistency-check.yml
>              moduleSymname: jexperience
Checks added. We install the modules from 8.0.0 upwards.

2023-04-26 19:03 UTC, julien-gagnon commented on packages/jahia/consistency-check.yml
> -                message: "Running augmented-search version is ${globals.runningVersion} instead of ${this.expectedASVersion}"
This has been corrected

2023-04-26 19:03 UTC, julien-gagnon commented on packages/jahia/consistency-check.yml
> -    - checkSAM
The checks are back in the package

2023-04-27 07:29 UTC, kevinvandel commented on packages/jahia/consistency-check.yml
> -    - checkSAM
Sorry to ask that since it's not in the scope of your ticket, but could you also fix the SAM version check? In PAAS-2318 (_Upgrade SAM to 2.6.0 on Jahia 8.1.2+_) @Ronan-Gorain forgot to update it (and @laurentfufu validated it, so that's a criminal conspiracy :stuck_out_tongue:)

2023-04-27 07:31 UTC, kevinvandel requested changes

2023-04-27 07:31 UTC, kevinvandel commented on packages/jahia/consistency-check.yml
>    checkJExperience:
While you're at it, could you please remove one new line (need only one)?

2023-04-27 10:52 UTC, julien-gagnon commented on packages/jahia/consistency-check.yml
> -    - checkSAM
@kevinvandel I think I already did ? Or there's something else to fix ?

2023-04-27 10:56 UTC, julien-gagnon commented on packages/jahia/consistency-check.yml
> -    - checkSAM
Nevermind, I updated the expected version but not the comment. My bad

2023-04-27 11:24 UTC, kevinvandel submitted a review, later dismissed

2023-04-27 11:45 UTC, kevinvandel approved these changes

2023-04-27 11:45 UTC, merged