Paas 1510 move backup to jelastic packages
Jahia/jelastic-packages pull request #7
Opened 2021-04-09 22:26 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1510

Short description:

Good luck :trollface:

2021-04-12 17:18 UTC, laurentfufu reviewed
(review not finished yet, very long :trollface: )

2021-04-12 17:18 UTC, laurentfufu commented on mixins/common.yml
> +        done
something is weird here

2021-04-12 17:18 UTC, laurentfufu commented on packages/common/auto_backup.yml
> +  text: blabla bla
maybe we can remove this... um... _placeholder_ :trollface:

2021-04-13 08:53 UTC, laurentfufu requested changes

2021-04-13 08:53 UTC, laurentfufu commented on packages/common/auto_backup.yml
> +logo: /images/jahia-logo-70x70.png
bad path

2021-04-13 08:53 UTC, laurentfufu commented on packages/common/auto_backup_control.yml
> +        backup_url: ${response.backup_url}
don't see where this global is used

2021-04-13 08:53 UTC, laurentfufu commented on packages/common/listbackup.yml
> +  - mixins/common.yml
bad path

2021-04-13 20:58 UTC, adoux commented on mixins/common.yml
> +        done
:man_shrugging: 
one of the files is in "elasticsearch" subfolder where all the others are in "common", that's why

2021-04-13 21:08 UTC, adoux commented on packages/common/auto_backup.yml
> +  text: blabla bla
Damn I did it earlier but the update must have been lost in the process :man_facepalming:

2021-04-13 21:09 UTC, adoux commented on packages/common/auto_backup.yml
> +logo: /images/jahia-logo-70x70.png
Good catch!

2021-04-13 21:14 UTC, adoux commented on packages/common/auto_backup_control.yml
> +        backup_url: ${response.backup_url}
Indeed, I removed that part!

2021-04-13 21:15 UTC, adoux commented on packages/common/listbackup.yml
> +  - mixins/common.yml
Good catch!

2021-04-14 12:29 UTC, laurentfufu requested changes

2021-04-14 12:29 UTC, laurentfufu commented on mixins/common.yml
> +        done
but maybe download only once the "elasticsearch" one will be enough ? :trollface: 
indentation is wrong but the curl for "elasticsearch.py" is down for each iteration in the for loop, so maybe shit line line 242 and 243 is the thing to do

2021-04-14 12:41 UTC, adoux commented on mixins/common.yml
> +        done
Oh damn, I'm King Dumb :man_facepalming:

2021-04-14 14:18 UTC, laurentfufu approved these changes

2021-04-14 14:18 UTC, merged