PAAS-1653: Fix custom check script for jahia_node_not_in_haproxy_pool monitor
Jahia/jelastic-packages pull request #70
Opened 2021-06-23 22:41 UTC by amitc-jahia

JIRA issue: https://jira.jahia.org/browse/PAAS-1653

Short description:

2021-06-28 13:40 UTC, kevinvandel requested changes

2021-06-28 13:40 UTC, kevinvandel commented on packages/jahia/migrations/migrate-to-v7.yaml
> +  - changeAccessLogPatternForJahiaNode            # PAAS-1653
We should add a BIG warning here that `changeAccessLogPatternForJahiaNode` will restart all jahia nodes. Or split the restart in a specific step

2021-06-28 21:22 UTC, amitc-jahia commented on packages/jahia/migrations/migrate-to-v7.yaml
> +  - changeAccessLogPatternForJahiaNode            # PAAS-1653
Update pattern and restart jahia steps have been split into 2 actions.

2021-06-29 06:38 UTC, kevinvandel approved these changes

2021-06-29 12:24 UTC, merged