PAAS-1321: improve haproxy conf management
Jahia/jelastic-packages pull request #74
Opened 2021-06-30 04:35 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1321

Short description:

2021-06-30 11:10 UTC, Ronan-Gorain requested changes

2021-06-30 11:10 UTC, Ronan-Gorain commented on packages/jahia/migrations/migrate-to-v7.yaml
> +        rm -rf /etc/haproxy/haproxy.cfg.d
I wonder if we should move it somewhere else instead. So we won't loose rewrites if something goes wrong. I know rewrites are probably in vault and/or in a backup, but if there is a issue on an environment where it was set before using vault, and that is not backed up, this will suck .

2021-06-30 14:59 UTC, adoux commented on assets/haproxy/haproxy-jahia-cloud.cfg
> +##CUSTOMER_RULES_START_HERE##
Good catch! Fixed

2021-06-30 14:59 UTC, adoux commented on assets/haproxy/haproxy_one_remaining_browsing.py
> +    HAPROXY_CONF_FILE = '/etc/haproxy/haproxy.cfg.jahia/jahia-cloud.cfg'
Good catch! Fixed

2021-06-30 14:59 UTC, adoux commented on mixins/haproxy.yml
> +          sed -i "/^backend bk_jahia$/a\ \ \ \ server ${env.appid}-${@i.id} ${@i.intIP}:80 check cookie s${@i.id}" /etc/haproxy/haproxy.cfg.jahia/jahia-cloud.cfg
Indeed, I added a "reload" parameter so we can reuse this action elsewhere

2021-06-30 15:00 UTC, adoux commented on mixins/haproxy.yml
> +        sed -i "/^backend proc$/a\ \ \ \ server ${env.appid}-${nodes.proc.first.id} ${nodes.proc.first.intIP}:80 check cookie s${nodes.proc.first.id}" /etc/haproxy/haproxy.cfg.jahia/jahia-cloud.cfg
Indeed, done!

2021-06-30 15:00 UTC, adoux commented on packages/jahia/migrations/migrate-to-v7.yaml
> +        rm -rf /etc/haproxy/haproxy.cfg.d
Not a bad idea, done!

2021-07-01 07:02 UTC, Ronan-Gorain submitted a review, later dismissed

2021-07-05 12:55 UTC, adoux commented
@Ronan-Gorain, rebase done!

2021-07-05 13:01 UTC, Ronan-Gorain approved these changes

2021-07-05 13:57 UTC, adoux commented
Rebase re-done!

2021-07-05 14:19 UTC, Ronan-Gorain approved these changes

2021-07-05 14:19 UTC, merged