PAAS-1325: allow Workato & IT OVH firewall IP addresses
Jahia/jelastic-packages pull request #8
Opened 2021-04-12 22:45 UTC by adoux

JIRA issue: https://jira.jahia.org/browse/PAAS-1325

Short description:

2021-04-13 07:08 UTC, kevinvandel submitted a review, later dismissed

2021-04-13 07:08 UTC, kevinvandel commented on packages/jcustomer/install.yml
>    jcustomer_env_version: 3
Since you created the "migrate-to-v4" package, you also need to increment the `jcustomer_env_version` here.

2021-04-13 07:13 UTC, Ronan-Gorain requested changes

2021-04-13 07:13 UTC, Ronan-Gorain commented on packages/jcustomer/migrations/migrate-to-v4.yaml
> +####
Useless as there is no need for parameters here

2021-04-13 07:13 UTC, Ronan-Gorain commented on packages/jcustomer/migrations/migrate-to-v4.yaml
> +        return {"result": 0, "UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES": "127.0.0.1,::1,${globals.workato_ip_adds},${globals.it_ovh_firewall_add}," + allowed_ips}
Unless I'm mistaken, the env var still needs to be updated. Also, maybe you just have to call the api in the script, no need to return it.

2021-04-13 14:09 UTC, adoux commented on packages/jcustomer/migrations/migrate-to-v4.yaml
> +        return {"result": 0, "UNOMI_THIRDPARTY_PROVIDER1_IPADDRESSES": "127.0.0.1,::1,${globals.workato_ip_adds},${globals.it_ovh_firewall_add}," + allowed_ips}
Very good catch, forgot the essential part :facepalm: 
Fixed

2021-04-13 14:10 UTC, adoux commented on packages/jcustomer/migrations/migrate-to-v4.yaml
> +####
Removed!

2021-04-13 14:10 UTC, adoux commented on packages/jcustomer/install.yml
>    jcustomer_env_version: 3
Good catch, fixed!

2021-08-05 13:30 UTC, laurentfufu approved these changes

2021-08-05 13:32 UTC, merged