PAAS-2642: Use provisioning API to handle RO/FRO
Jahia/jelastic-packages pull request #839
Opened 2023-10-27 13:38 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-2642

Short description:

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2023-10-27 14:14 UTC, laurentfufu commented on mixins/jahia.yml
> +        wc -l /opt/tomcat/logs/catalina.out |awk '{print $1}'
```suggestion
        wc -l /opt/tomcat/logs/catalina.out |  awk '{print $1}'
```

2023-10-27 14:23 UTC, Ronan-Gorain commented on mixins/jahia.yml
> +        wc -l /opt/tomcat/logs/catalina.out |awk '{print $1}'
Fixed

2023-10-27 17:18 UTC, julien-gagnon requested changes

2023-10-27 17:18 UTC, julien-gagnon commented on mixins/jahia.yml
> +            systemctl restart rsyslog crond datadog-agent
I'm not sure I understand about this change in this PR. Could it be a mistake ?

2023-10-30 13:46 UTC, laurentfufu commented on mixins/jahia.yml
> +            systemctl restart rsyslog crond datadog-agent
I guess it is yes

2023-10-30 14:01 UTC, laurentfufu commented on mixins/jahia.yml
> +            systemctl restart rsyslog crond datadog-agent
should be ok now

2023-10-30 17:21 UTC, julien-gagnon approved these changes

2023-10-30 17:21 UTC, merged