COPS-953: fix the way we fetch proxysql password in hn_nodes_list.py.
Jahia/jelastic-packages pull request #857
Opened 2023-11-21 13:05 UTC by Ronan-Gorain

Handle storage nodes in stop/start-node.yaml

JIRA issue: https://jira.jahia.org/browse/COPS-953

Short description:

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2023-11-21 13:25 UTC, laurentfufu commented on assets/common/hn_nodes_list.py
> +    command = "mysql -NB -u admin -p$(grep password /etc/datadog-agent/conf.d/proxysql.d/conf.yaml| awk '{print $2}') -P 6032 -h 127.0.0.1 " \
```suggestion
    command = "mysql -NB -u admin -p$(awk '$1=="password:" '{print $2}' /etc/datadog-agent/conf.d/proxysql.d/conf.yaml) -P 6032 -h 127.0.0.1 " \
```

2023-11-21 13:32 UTC, Ronan-Gorain commented on assets/common/hn_nodes_list.py
> +    command = "mysql -NB -u admin -p$(grep password /etc/datadog-agent/conf.d/proxysql.d/conf.yaml| awk '{print $2}') -P 6032 -h 127.0.0.1 " \
updated

2023-11-22 09:17 UTC, laurentfufu requested changes

2023-11-22 09:17 UTC, laurentfufu commented on assets/common/hn_nodes_list.py
> +    command = "mysql -NB -u admin -p$(awk '$1=="password:" '{print $2}' /etc/datadog-agent/conf.d/proxysql.d/conf.yaml) -P 6032 -h 127.0.0.1 " \
```suggestion
    command = "mysql -NB -u admin -p$(awk '$1=="password:" {print $2}' /etc/datadog-agent/conf.d/proxysql.d/conf.yaml) -P 6032 -h 127.0.0.1 " \
```
:grin:

2023-11-22 09:17 UTC, laurentfufu commented on assets/common/hn_nodes_list.py
> +    command = "mysql -NB -u admin -p$(awk '$1=="password:" '{print $2}' /etc/datadog-agent/conf.d/proxysql.d/conf.yaml) -P 6032 -h 127.0.0.1 " \
never trust me :trollface:

2023-11-27 10:23 UTC, Ronan-Gorain commented on assets/common/hn_nodes_list.py
> +    command = "mysql -NB -u admin -p$(awk '$1=="password:" '{print $2}' /etc/datadog-agent/conf.d/proxysql.d/conf.yaml) -P 6032 -h 127.0.0.1 " \
Fixed :)

2023-11-27 10:25 UTC, merged