PAAS-2739 retry sending logs to logs bucket if an error occurs
Jahia/jelastic-packages pull request #900
Opened 2023-12-19 15:38 UTC by laurentfufu

JIRA issue: https://jira.jahia.org/browse/PAAS-2739

Short description:

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2023-12-20 08:06 UTC, kevinvandel approved these changes

2023-12-20 09:29 UTC, Ronan-Gorain requested changes

2023-12-20 09:29 UTC, Ronan-Gorain commented on packages/jcustomer/migrations/migrate-to-v27.yaml
> +    cmd[bl, cp, proc, sqldb, storage]: |-
There are no such node groups in jcustomer environments :)

2023-12-20 14:08 UTC, laurentfufu commented on packages/jcustomer/migrations/migrate-to-v27.yaml
> +    cmd[bl, cp, proc, sqldb, storage]: |-
indeed !

also move to migration v28 manifest :grin:

2023-12-21 10:24 UTC, Ronan-Gorain approved these changes

2023-12-21 10:24 UTC, merged