PAAS-2869: fix jcustomer 2.4 lost aliases bug at restoration
Jahia/jelastic-packages pull request #987
Opened 2024-03-28 16:00 UTC by Ronan-Gorain

JIRA issue: https://jira.jahia.org/browse/PAAS-2869

Short description:

**Don't forget** to update the README and any related documentation if needed: https://confluence.jahia.com/x/bYATAg

2024-03-28 16:37 UTC, laurentfufu requested changes

2024-03-28 16:37 UTC, laurentfufu commented on packages/common/restore.yml
> +        prefix=$(curl -s -u $__secret__ec_admin_credentials -XGET "https://$UNOMI_ELASTICSEARCH_ADDRESSES/_snapshot/${env.shortdomain}/${timestamp}_manual"|jq ".snapshots[0].indices[0]" -r | sed 's/\
```suggestion
        prefix=$(curl -s -u $__secret__ec_admin_credentials -XGET "https://$UNOMI_ELASTICSEARCH_ADDRESSES/_snapshot/${env.shortdomain}/${timestamp}_${settings.backtype}" | jq '.snapshots[0].indices[0]' -r | sed 's/\(.*__jc\).*/\1/')
```

The important one is the backup type of course, the _quote_ things is more for readability

2024-03-29 07:10 UTC, Ronan-Gorain commented on packages/common/restore.yml
> +        prefix=$(curl -s -u $__secret__ec_admin_credentials -XGET "https://$UNOMI_ELASTICSEARCH_ADDRESSES/_snapshot/${env.shortdomain}/${timestamp}_manual"|jq ".snapshots[0].indices[0]" -r | sed 's/\
ouch... fixed

2024-03-29 08:55 UTC, laurentfufu approved these changes

2024-03-29 08:55 UTC, merged